import test from 'node:test';
import assert from 'node:assert/strict';
import { F } from './harness.mjs';

const {ADJACENCY,REGION_TERRITORIES,TERRITORIES,SequenceRng,SeededRng,STARTING_ARMIES,armiesOwned,attack,autoAllocateStartingArmies,calculateReinforcements,checkVictory,createGame,endTurn,findRedeemableSet,draftTerritory,finalizeSetup,fortify,redeemCards,regionsControlled,resolveClash,tradeBonusForIndex,currentPlayer,runBotTurn,scoreAttackHard,shouldHardBotRedeem}=F;
function readyState(players=2,winMode='domination'){
  const p=Array.from({length:players},(_,i)=>({id:`p${i+1}`,name:`P${i+1}`}));
  const state=createGame({players:p,winMode,assignment:'random',seed:42},new SeededRng(42));
  for(const id of Object.keys(state.setup.remaining)) state.setup.remaining[id]=0;
  finalizeSetup(state,new SeededRng(9));
  return state;
}

test('map has 30–45 territories, symmetric adjacency, and is connected',()=>{
  assert.ok(TERRITORIES.length>=30&&TERRITORIES.length<=45);
  for(const [id,neighbors] of Object.entries(ADJACENCY)){assert.ok(neighbors.length>=2);for(const n of neighbors)assert.ok(ADJACENCY[n]?.includes(id),`${id}<->${n}`);}
  const seen=new Set([TERRITORIES[0].id]),q=[TERRITORIES[0].id];while(q.length){for(const n of ADJACENCY[q.shift()])if(!seen.has(n)){seen.add(n);q.push(n);}}assert.equal(seen.size,TERRITORIES.length);
});
test('reinforcement calculation includes region bonus',()=>{const s=readyState();for(const id of REGION_TERRITORIES.aurelian)s.territories[id]={owner:'p1',armies:2};const r=calculateReinforcements(s,'p1');assert.ok(r.base>=3);assert.ok(r.regionBonus>=4);assert.equal(r.total,r.base+r.regionBonus);assert.ok(regionsControlled(s,'p1').includes('aurelian'));});
test('combat is deterministic with injected RNG',()=>{const r=resolveClash({attackerArmies:6,defenderArmies:4,attackCommit:3,defendCommit:2},new SequenceRng([.99,.8,.1,.7,.2]));assert.deepEqual(Array.from(r.attackRolls),[6,5,1]);assert.deepEqual(Array.from(r.defendRolls),[5,2]);assert.equal(r.defenderLosses,2);assert.equal(r.attackerLosses,1);});
test('capture keeps origin and destination occupied',()=>{const s=readyState();s.phase='attack';s.currentPlayerIndex=0;s.territories.cinderfall={owner:'p1',armies:6};s.territories.ashridge={owner:'p2',armies:1};const r=attack(s,{from:'cinderfall',to:'ashridge',attackCommit:3,defendCommit:1},new SequenceRng([.99,.8,.7,.1]));assert.equal(r.captured,true);assert.equal(s.territories.ashridge.owner,'p1');assert.ok(s.territories.cinderfall.armies>=1);assert.ok(s.territories.ashridge.armies>=1);});
test('cards recognize matching, mixed and prism sets with escalating curve',()=>{assert.deepEqual(Array.from(findRedeemableSet([{symbol:'forge'},{symbol:'forge'},{symbol:'forge'}])),[0,1,2]);assert.deepEqual(Array.from(findRedeemableSet([{symbol:'forge'},{symbol:'beacon'},{symbol:'aegis'}])),[0,1,2]);assert.deepEqual(Array.from(findRedeemableSet([{symbol:'forge'},{symbol:'beacon'},{symbol:'prism'}])),[0,1,2]);assert.equal(findRedeemableSet([{symbol:'forge'},{symbol:'forge'},{symbol:'beacon'}]),null);assert.deepEqual([0,1,2,3,4,5,6].map(tradeBonusForIndex),[4,6,9,13,18,24,31]);});
test('victory checks domination capital and mission',()=>{const s=readyState(2,'domination');for(const id of Object.keys(s.territories))s.territories[id]={owner:'p1',armies:1};assert.equal(checkVictory(s,'p1'),'World domination');s.settings.winMode='capital';s.players[0].capital=TERRITORIES[0].id;s.players[1].capital=TERRITORIES[1].id;assert.match(checkVictory(s,'p1'),/Capital ascendancy/);s.settings.winMode='mission';s.players[0].mission={type:'territories',target:14,label:'Hold 14 territories at once'};assert.match(checkVictory(s,'p1'),/Objective completed/);});
test('fortification traverses owned chain and leaves one behind',()=>{const s=readyState();s.phase='fortify';s.currentPlayerIndex=0;for(const id of ['solhaven','amberstep','brightscar'])s.territories[id]={owner:'p1',armies:1};s.territories.solhaven.armies=5;fortify(s,{from:'solhaven',to:'brightscar',amount:4});assert.equal(s.territories.solhaven.armies,1);assert.equal(s.territories.brightscar.armies,5);});
test('seeded RNG repeats',()=>{const a=new SeededRng(12345),b=new SeededRng(12345);assert.deepEqual(Array.from({length:20},()=>a.int(1,100)),Array.from({length:20},()=>b.int(1,100)));});
test('starting armies match configured totals for 2–6 players',()=>{for(let count=2;count<=6;count++){const players=Array.from({length:count},(_,i)=>({id:`p${i+1}`}));const rng=new SeededRng(500+count);const s=createGame({players,assignment:'random',seed:500+count},rng);autoAllocateStartingArmies(s,rng);for(const p of s.players)assert.equal(armiesOwned(s,p.id),STARTING_ARMIES[count]);}});
test('draft rotates and rejects claimed territory',()=>{const s=createGame({players:[{id:'p1'},{id:'p2'}],assignment:'draft',seed:7},new SeededRng(7));const a=TERRITORIES[0].id,b=TERRITORIES[1].id;draftTerritory(s,'p1',a);assert.throws(()=>draftTerritory(s,'p1',b),/Not this player/);draftTerritory(s,'p2',b);assert.throws(()=>draftTerritory(s,'p1',a),/not available/i);});
test('attack rejects non-adjacent target',()=>{const s=readyState();s.phase='attack';s.currentPlayerIndex=0;s.territories.solhaven={owner:'p1',armies:5};s.territories.moonshoal={owner:'p2',armies:1};assert.throws(()=>attack(s,{from:'solhaven',to:'moonshoal',attackCommit:2,defendCommit:1},new SeededRng(1)),/not adjacent/i);});
test('redeeming set mutates hand discard curve and reinforcements',()=>{const s=readyState(),p=s.players[0];s.currentPlayerIndex=0;s.phase='reinforce';s.reinforcementPool=3;p.cards=[{id:'a',symbol:'forge'},{id:'b',symbol:'beacon'},{id:'c',symbol:'aegis'}];assert.equal(redeemCards(s,p.id),4);assert.equal(p.cards.length,0);assert.equal(s.discard.length,3);assert.equal(s.tradeCount,1);assert.equal(s.reinforcementPool,7);});
test('score mode ends at round limit',()=>{const s=readyState(2,'score');s.settings.turnLimit=1;s.phase='turn-end';s.turnNumber=1;s.currentPlayerIndex=0;endTurn(s);s.phase='turn-end';s.currentPlayerIndex=1;endTurn(s);assert.ok(s.winner);assert.match(s.winner.reason,/Highest score after 1 rounds/);});
test('hard bot prefers weak target to fortified target',()=>{const s=createGame({players:[{id:'p1',type:'bot',difficulty:'hard'},{id:'p2'}],seed:2},new SeededRng(2));autoAllocateStartingArmies(s,new SeededRng(3));s.phase='attack';s.currentPlayerIndex=0;s.territories.cinderfall={owner:'p1',armies:7};s.territories.ashridge={owner:'p2',armies:1};s.territories['red-basin']={owner:'p2',armies:6};assert.ok(scoreAttackHard(s,'p1','cinderfall','ashridge')>scoreAttackHard(s,'p1','cinderfall','red-basin'));});
test('random bot games retain occupied valid territories',()=>{for(let seed=1;seed<=12;seed++){const rng=new SeededRng(seed);const s=createGame({players:[{id:'a',type:'bot',difficulty:'easy'},{id:'b',type:'bot',difficulty:'medium'},{id:'c',type:'bot',difficulty:'hard'}],seed,winMode:'score',turnLimit:8},rng);autoAllocateStartingArmies(s,rng);let guard=0;while(!s.winner&&guard<80){assert.equal(currentPlayer(s).type,'bot');runBotTurn(s,rng,6);guard++;for(const t of Object.values(s.territories)){assert.ok(t.owner);assert.ok(t.armies>=1);}}assert.ok(s.winner||guard===80);}});
test('hard bot times card redemption',()=>{const rng=new SeededRng(77);const s=createGame({players:[{id:'p1',type:'bot',difficulty:'hard'},{id:'p2'}],seed:77},rng);autoAllocateStartingArmies(s,rng);for(const id of Object.keys(s.territories))s.territories[id]={owner:'p2',armies:1};s.territories.solhaven={owner:'p1',armies:20};s.territories['kestrel-vale']={owner:'p1',armies:20};s.currentPlayerIndex=0;s.phase='reinforce';s.players[0].cards=[{id:'1',symbol:'forge'},{id:'2',symbol:'forge'},{id:'3',symbol:'forge'}];assert.equal(shouldHardBotRedeem(s,'p1'),false);s.players[0].cards.push({id:'4',symbol:'beacon'},{id:'5',symbol:'aegis'});assert.equal(shouldHardBotRedeem(s,'p1'),true);});
