(()=>{'use strict';
const app=document.querySelector('#app');
const SUITS={copper:{label:'Copper',size:2,rents:[1,2],color:'#936143'},sky:{label:'Sky',size:3,rents:[1,2,3],color:'#77bddd'},rose:{label:'Rose',size:3,rents:[1,2,4],color:'#c56c96'},ember:{label:'Ember',size:3,rents:[1,3,5],color:'#d77738'},ruby:{label:'Ruby',size:3,rents:[2,3,6],color:'#c64b49'},gold:{label:'Gold',size:3,rents:[2,4,6],color:'#d4b84c'},grove:{label:'Grove',size:3,rents:[2,4,7],color:'#5b9865'},indigo:{label:'Indigo',size:2,rents:[3,8],color:'#4665a7'},station:{label:'Station',size:4,rents:[1,2,3,4],color:'#6f7c78'},service:{label:'Service',size:2,rents:[1,2],color:'#8d7caf'}};
const PV={copper:1,sky:1,rose:2,ember:2,ruby:3,gold:3,grove:4,indigo:4,station:2,service:2};
let seq=1,state=null,screen='home',me='human',peer=null,conn=null,conns=new Map(),peerMap=new Map(),lobby=null;
const id=()=>`c${seq++}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>globalThis.structuredClone?structuredClone(x):JSON.parse(JSON.stringify(x));
function money(v){return{id:id(),kind:'money',name:`${v} Credit`,value:v}}
function prop(s){return{id:id(),kind:'property',name:`${SUITS[s].label} Asset`,value:PV[s],suit:s}}
function flex(){return{id:id(),kind:'wild',name:'Flexible Asset',value:2,suit:null}}
function act(type,name,v=1){return{id:id(),kind:'action',type,name,value:v}}
function deck(){seq=1;const d=[];for(const[v,n]of[[1,6],[2,5],[3,3],[4,3],[5,2],[10,1]])for(let i=0;i<n;i++)d.push(money(v));for(const[s,m]of Object.entries(SUITS))for(let i=0;i<m.size;i++)d.push(prop(s));for(let i=0;i<8;i++)d.push(flex());for(let i=0;i<10;i++)d.push(act('refill','Refill',1));for(let i=0;i<12;i++)d.push(act('invoice','Invoice',1));for(let i=0;i<3;i++)d.push(act('collection','Collection Day',2));for(let i=0;i<3;i++)d.push(act('demand','Demand Payment',3));for(let i=0;i<3;i++)d.push(act('snatch','Snatch',3));for(let i=0;i<3;i++)d.push(act('trade','Trade Order',3));for(let i=0;i<2;i++)d.push(act('takeover','Hostile Takeover',5));for(let i=0;i<2;i++)d.push(act('multiplier','Multiplier',1));return d}
function shuffle(a){a=a.map(x=>({...x}));for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function player(x){return{id:x.id,name:x.name,bot:!!x.bot,hand:[],bank:[],props:[]}}
function draw(p,n){for(let i=0;i<n;i++){if(!state.deck.length&&state.discard.length){state.deck=shuffle(state.discard);state.discard=[]}const c=state.deck.pop();if(c)p.hand.push(c)}}
function current(){return state.players[state.current]}
function count(p,s){return p.props.filter(c=>c.suit===s).length}
function full(p,s){return count(p,s)>=SUITS[s].size}
function sets(p){return Object.keys(SUITS).filter(s=>full(p,s)).length}
function begin(){const p=current();draw(p,p.hand.length?2:5);state.actions=3;state.mult=1;state.log.push(`${p.name} drew cards.`)}
function create(ps){state={v:2,deck:shuffle(deck()),discard:[],players:ps.map(player),current:0,actions:3,turn:1,mult:1,winner:null,log:[]};state.players.forEach(p=>draw(p,5));begin()}
function requireTurn(pid){if(state.winner)throw Error('Game over');if(current().id!==pid)throw Error('Not your turn');if(state.actions<=0)throw Error('No actions left')}
function take(p,cid){const i=p.hand.findIndex(c=>c.id===cid);if(i<0)throw Error('Card not in hand');return p.hand.splice(i,1)[0]}
function win(p){if(sets(p)>=3){state.winner=p.id;state.log.push(`${p.name} completed three portfolios.`)}}
function playProperty(pid,cid,suit){requireTurn(pid);const p=state.players.find(x=>x.id===pid),c=take(p,cid);if(!['property','wild'].includes(c.kind))throw Error('Not an asset');if(c.kind==='wild'){if(!SUITS[suit])throw Error('Choose a group');c.suit=suit}p.props.push(c);state.actions--;state.log.push(`${p.name} placed ${SUITS[c.suit].label}.`);win(p)}
function bank(pid,cid){requireTurn(pid);const p=state.players.find(x=>x.id===pid),c=p.hand.find(x=>x.id===cid);if(!c)throw Error('Card not in hand');if(['property','wild'].includes(c.kind))throw Error('Assets cannot be banked');p.bank.push(take(p,cid));state.actions--;state.log.push(`${p.name} banked ${c.value}.`)}
function assets(p){return[...p.bank,...p.props].reduce((n,c)=>n+c.value,0)}
function pay(from,to,amt){amt=Math.min(amt,assets(from));const pool=[...from.bank.map(c=>['bank',c]),...from.props.map(c=>['props',c])].sort((a,b)=>a[1].value-b[1].value);let paid=0;while(pool.length&&paid<amt){const[z,c]=pool.shift(),i=from[z].findIndex(x=>x.id===c.id);if(i<0)continue;from[z].splice(i,1);to[z==='props'?'props':'bank'].push(c);paid+=c.value}state.log.push(`${from.name} paid ${to.name} ${paid}.`);win(to)}
function loose(p){return p?.props.filter(c=>!full(p,c.suit))??[]}
function target(pid){return state.players.filter(p=>p.id!==pid).sort((a,b)=>assets(b)-assets(a))[0]}
function playAction(pid,cid,opt={}){requireTurn(pid);const p=state.players.find(x=>x.id===pid),c=p.hand.find(x=>x.id===cid);if(!c||c.kind!=='action')throw Error('Not an action');const t=opt.target&&state.players.find(x=>x.id===opt.target)||target(pid);if(c.type==='multiplier'){take(p,cid);state.discard.push(c);state.mult=2;state.actions--;state.log.push(`${p.name} primed a multiplier.`);return}take(p,cid);state.discard.push(c);state.actions--;if(c.type==='refill'){draw(p,2);state.log.push(`${p.name} refilled two.`)}else if(c.type==='collection'){state.players.filter(x=>x!==p).forEach(x=>pay(x,p,2));state.log.push(`${p.name} ran Collection Day.`)}else if(c.type==='demand'){if(t)pay(t,p,5)}else if(c.type==='invoice'){const s=opt.suit||Object.keys(SUITS).filter(s=>count(p,s)).sort((a,b)=>SUITS[b].rents[Math.min(count(p,b),SUITS[b].size)-1]-SUITS[a].rents[Math.min(count(p,a),SUITS[a].size)-1])[0];if(!s)throw Error('Need an asset to invoice');const r=SUITS[s].rents[Math.min(count(p,s),SUITS[s].size)-1]*state.mult;state.mult=1;state.players.filter(x=>x!==p).forEach(x=>pay(x,p,r));state.log.push(`${p.name} invoiced ${r}.`)}else if(c.type==='snatch'){const x=loose(t)[0];if(!x)throw Error('No loose asset');t.props=t.props.filter(q=>q.id!==x.id);p.props.push(x);state.log.push(`${p.name} snatched an asset.`);win(p)}else if(c.type==='trade'){const a=loose(p)[0],b=loose(t)[0];if(!a||!b)throw Error('Both sides need loose assets');p.props=p.props.filter(x=>x.id!==a.id);t.props=t.props.filter(x=>x.id!==b.id);p.props.push(b);t.props.push(a);state.log.push(`${p.name} forced a trade.`);win(p);win(t)}else if(c.type==='takeover'){const s=t&&Object.keys(SUITS).find(s=>full(t,s));if(!s)throw Error('No complete portfolio to acquire');const xs=t.props.filter(x=>x.suit===s);t.props=t.props.filter(x=>x.suit!==s);p.props.push(...xs);state.log.push(`${p.name} completed a takeover.`);win(p)}}
function end(pid){if(current().id!==pid)throw Error('Not your turn');const p=current();while(p.hand.length>7)state.discard.push(p.hand.pop());state.current=(state.current+1)%state.players.length;state.turn++;begin()}
function botTurn(p){let guard=0;while(current()===p&&!state.winner&&guard++<8){if(state.actions<=0){end(p.id);break}const pr=p.hand.find(c=>c.kind==='property'||c.kind==='wild');if(pr){const s=pr.suit||Object.keys(SUITS).sort((a,b)=>count(p,b)/SUITS[b].size-count(p,a)/SUITS[a].size)[0];playProperty(p.id,pr.id,s);continue}const opp=target(p.id);let a=p.hand.find(c=>c.kind==='action'&&c.type==='takeover'&&opp&&Object.keys(SUITS).some(s=>full(opp,s)))||p.hand.find(c=>c.kind==='action'&&['invoice','refill','demand','collection','snatch'].includes(c.type));if(a){try{playAction(p.id,a.id)}catch{bank(p.id,a.id)}continue}const b=p.hand.filter(c=>c.kind!=='property'&&c.kind!=='wild').sort((x,y)=>y.value-x.value)[0];if(b){bank(p.id,b.id);continue}end(p.id)}}
function suitPick(){const keys=Object.keys(SUITS),n=prompt('Choose asset group:\n'+keys.map((s,i)=>`${i+1}. ${SUITS[s].label}`).join('\n'),'1');return keys[Number(n)-1]}
function actionFor(c){if(!c)return null;if(c.kind==='money')return{type:'bank',id:c.id};if(c.kind==='property')return{type:'prop',id:c.id,suit:c.suit};if(c.kind==='wild')return{type:'prop',id:c.id,suit:suitPick()};if(c.kind==='action')return{type:'action',id:c.id};return null}
function command(cmd,pid=me){if(!cmd)return;if(conn&&!isHost()){conn.send({type:'cmd',cmd,pid});return}applyCmd(cmd,pid);sync()}
function applyCmd(c,pid){try{if(c.type==='bank')bank(pid,c.id);else if(c.type==='prop')playProperty(pid,c.id,c.suit);else if(c.type==='action')playAction(pid,c.id,c.opt);else if(c.type==='end')end(pid);render();runBots()}catch(e){alert(e.message)}}
function runBots(){if(!state||state.winner)return;const p=current();if(p.bot)setTimeout(()=>{botTurn(p);sync();render();runBots()},250)}
function stateViewFor(pid){if(!state)return null;const view=clone(state);view.deck=Array(state.deck.length).fill(null);view.players.forEach(p=>{if(p.id!==pid)p.hand=Array(p.hand.length).fill(null)});return view}
function sync(){if(!peer||!isHost())return;for(const[peerId,c]of conns)if(c.open){const pid=peerMap.get(peerId);c.send({type:'state',state:stateViewFor(pid),lobby})}}
function isHost(){return lobby?.hostId===me}
function roomCode(){return Math.random().toString(36).slice(2,7).toUpperCase()}
function ensurePeer(cb){if(window.Peer)return cb();const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.async=true;s.onload=cb;s.onerror=()=>alert('Online service failed to load');document.head.append(s)}
function host(){ensurePeer(()=>{const code=roomCode();me='host';lobby={code,hostId:me,players:[{id:me,name:'Host'}]};peer=new Peer('dealroom-v2-'+code.toLowerCase());peer.on('open',()=>{screen='lobby';render()});peer.on('connection',c=>{c.on('data',d=>{if(d?.type==='join'){const incoming=String(d.p?.id||'').slice(0,40);if(!incoming||lobby.players.some(x=>x.id===incoming)||lobby.players.length>=5)return;const p={id:incoming,name:String(d.p?.name||'Player').slice(0,20)};lobby.players.push(p);conns.set(c.peer,c);peerMap.set(c.peer,p.id);sync();render()}else if(d?.type==='cmd'){const pid=peerMap.get(c.peer);if(pid&&pid===d.pid){applyCmd(d.cmd,pid);sync()}}});c.on('close',()=>{const pid=peerMap.get(c.peer);peerMap.delete(c.peer);conns.delete(c.peer);if(lobby&&!state)lobby.players=lobby.players.filter(p=>p.id!==pid);render()})});peer.on('error',()=>alert('Room could not be opened. Try a new room code.'))})}
function join(){const code=(document.querySelector('#room')?.value||'').trim().toUpperCase(),name=(document.querySelector('#name')?.value||'Player').trim().slice(0,20)||'Player';if(!code)return;ensurePeer(()=>{me='g'+Math.random().toString(36).slice(2,9);peer=new Peer();peer.on('open',()=>{conn=peer.connect('dealroom-v2-'+code.toLowerCase(),{reliable:true});conn.on('open',()=>conn.send({type:'join',p:{id:me,name}}));conn.on('data',d=>{if(d?.type==='state'){state=d.state;lobby=d.lobby;screen=state?'game':'lobby';render()}});conn.on('close',()=>alert('Host connection closed.'))});peer.on('error',()=>alert('Could not connect to the room.'))})}
function startSolo(){me='human';lobby=null;create([{id:me,name:'You'},{id:'bot',name:'DealBot',bot:true}]);screen='game';render();runBots()}
function addBot(){if(!isHost()||lobby.players.length>=5)return;lobby.players.push({id:'bot'+lobby.players.length,name:'Bot '+lobby.players.length,bot:true});sync();render()}
function startLobby(){if(!isHost()||lobby.players.length<2)return;create(lobby.players);screen='game';sync();render();runBots()}
function setsHtml(p){const a=Object.keys(SUITS).filter(s=>count(p,s));return a.map(s=>`<span class="set"><i class="dot" style="--c:${SUITS[s].color}"></i>${SUITS[s].label} ${count(p,s)}/${SUITS[s].size}${full(p,s)?' ✓':''}</span>`).join('')||'<span class="meta">No assets</span>'}
function cardHtml(c,can){if(!c)return'';const color=c.suit?SUITS[c.suit].color:c.kind==='action'?'#d2ad4e':c.kind==='money'?'#69a57b':'#7768a8';return`<div class="card" style="--c:${color}"><div><div class="band"></div><div class="kind">${esc(c.kind)}</div><div class="cardname">${esc(c.name)}</div></div><div><span class="value">${c.value}</span>${can?`<button data-id="${c.id}" data-play>Play</button>${c.kind==='action'||c.kind==='money'?`<button data-id="${c.id}" data-bank>Bank</button>`:''}`:''}</div></div>`}
function layout(x){return`<main class="shell"><header class="top"><div class="brand"><b class="mark">DR</b> Deal Room</div><span class="pill">MIT-aligned · original deck</span></header>${x}</main>`}
function home(){app.innerHTML=layout(`<section class="hero"><div class="ey">OPEN-SOURCE PROPERTY-SET CARD GAME</div><h1>Build portfolios.<br>Break deals.</h1><p class="lede">A fast browser card game aligned to the permissively licensed DealBench state model while keeping original names, artwork and presentation.</p><div class="modes"><button class="mode" id="solo"><b>Vs computer</b><span>Two-player game with a tactical bot.</span></button><button class="mode" id="host"><b>Host online</b><span>Create a peer-to-peer room.</span></button><button class="mode" id="join"><b>Join room</b><span>Enter a code from a friend.</span></button></div><div class="row" id="joinbox" hidden><input id="name" value="Player" aria-label="Name"><input id="room" placeholder="ROOM" aria-label="Room code"><button class="btn primary" id="joinnow">Join</button></div><p class="privacy">Online rooms are host-authoritative. Each peer receives only its own hand; opponent hands and draw-pile order are redacted from network snapshots.</p><p class="source">Each turn: draw, play up to three cards, bank credits/actions, and complete three different portfolios. <a href="./THIRD_PARTY_NOTICES.md">Source lineage</a>.</p></section>`);document.querySelector('#solo').onclick=startSolo;document.querySelector('#host').onclick=host;document.querySelector('#join').onclick=()=>document.querySelector('#joinbox').hidden=false;document.querySelector('#joinnow').onclick=join}
function lobbyView(){app.innerHTML=layout(`<section class="hero"><div class="ey">ONLINE ROOM</div><h1>${esc(lobby.code)}</h1><p class="lede">Share this code. The host browser stays authoritative.</p><div class="players">${lobby.players.map(p=>`<div class="player"><b>${esc(p.name)}</b><div class="meta">${p.bot?'Computer':'Human'}</div></div>`).join('')}</div>${isHost()?`<div class="row"><button class="btn" id="add">Add bot</button><button class="btn primary" id="start">Start game</button></div>`:'<p class="meta">Waiting for host…</p>'}</section>`);document.querySelector('#add')?.addEventListener('click',addBot);document.querySelector('#start')?.addEventListener('click',startLobby)}
function gameView(){const p=state.players.find(x=>x.id===me)||state.players[0],act=current(),can=act.id===me&&!state.winner;app.innerHTML=layout(`<div class="gamehead"><div><h2>${esc(act.name)} to play</h2><div class="sub">Turn ${state.turn} · ${state.actions} actions left · ${state.deck.length} cards in draw pile</div></div><button class="btn" id="quit">New game</button></div><section class="board"><div class="table"><div class="players">${state.players.filter(x=>x.id!==p.id).map(x=>`<div class="player ${x===act?'on':''}"><b>${esc(x.name)}</b><div class="meta">${x.hand.length} cards · ${x.bank.reduce((n,c)=>n+c.value,0)} bank · ${sets(x)}/3 portfolios</div><div class="sets">${setsHtml(x)}</div></div>`).join('')}</div><div class="your"><b>${esc(p.name)}</b><div class="meta">${p.bank.reduce((n,c)=>n+c.value,0)} bank · ${sets(p)}/3 portfolios</div><div class="sets">${setsHtml(p)}</div><div class="hand">${p.hand.map(c=>cardHtml(c,can&&state.actions>0)).join('')}</div><div class="row"><button class="btn primary" id="end" ${can?'':'disabled'}>End turn</button></div></div></div><aside class="side"><h3>HOW TO WIN</h3><p class="meta">Complete three different portfolios. Flexible Assets can join any group.</p><h3>ACTIVITY</h3><div class="log">${state.log.slice(-26).reverse().map(x=>`<div>${esc(x)}</div>`).join('')}</div><p class="source"><a href="./THIRD_PARTY_NOTICES.md">MIT upstream notice</a></p></aside></section>${state.winner?`<div class="winner"><div><div class="ey">GAME OVER</div><h2>${esc(state.players.find(x=>x.id===state.winner)?.name)} wins</h2><button class="btn primary" id="again">Play again</button></div></div>`:''}`);document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const c=p.hand.find(x=>x?.id===b.dataset.id);command(actionFor(c))});document.querySelectorAll('[data-bank]').forEach(b=>b.onclick=()=>command({type:'bank',id:b.dataset.id}));document.querySelector('#end').onclick=()=>command({type:'end'});document.querySelector('#quit').onclick=()=>{peer?.destroy?.();peer=conn=null;conns.clear();peerMap.clear();state=null;screen='home';render()};document.querySelector('#again')?.addEventListener('click',()=>{state=null;screen='home';render()})}
function render(){if(screen==='home')home();else if(screen==='lobby')lobbyView();else gameView()}
render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
