(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TwentyOneEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function rng(seed){let x=(Number(seed)>>>0)||0x12345678;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}
function makeShoe(decks,seed){decks=Math.max(1,Math.min(8,Number(decks)||6));const a=[];for(let d=0;d<decks;d++)for(let suit=0;suit<4;suit++)for(let rank=1;rank<=13;rank++)a.push(rank);const r=rng(seed==null?Date.now():seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cardValue(rank){return rank===1?11:Math.min(10,rank)}function handValue(cards){let total=cards.reduce((n,c)=>n+cardValue(c),0),aces=cards.filter(c=>c===1).length,soft=aces>0;while(total>21&&aces>0){total-=10;aces--;soft=aces>0}return{total,soft:soft&&total<=21,bust:total>21}}
function isBlackjack(hand){return hand.cards.length===2&&!hand.fromSplit&&handValue(hand.cards).total===21}
function hiLo(rank){const v=cardValue(rank);return v>=2&&v<=6?1:v===10||rank===1?-1:0}
function defaultRules(o){o=o||{};return{decks:Math.max(1,Math.min(8,Number(o.decks)||6)),dealerHitsSoft17:!!o.dealerHitsSoft17,doubleAfterSplit:o.doubleAfterSplit!==false,maxSplits:Math.max(0,Math.min(3,o.maxSplits==null?3:Number(o.maxSplits))),hitSplitAces:!!o.hitSplitAces,blackjackPayout:Number(o.blackjackPayout)||1.5,surrender:o.surrender!==false,insurance:o.insurance!==false,penetration:Math.max(.25,Math.min(.9,Number(o.penetration)||.75))}}
function draw(s){if(!s.shoe.length)throw new Error('Shoe empty');const c=s.shoe.pop();s.runningCount+=hiLo(c);s.cardsSeen++;return c}
function createSession(o){const rules=defaultRules(o),shoe=makeShoe(rules.decks,o&&o.seed);return{rules,shoe,initialShoeSize:shoe.length,runningCount:0,cardsSeen:0,score:0,rounds:0,wins:0,losses:0,pushes:0,seed:o&&o.seed}}
function cloneSession(s){return{...s,rules:{...s.rules},shoe:s.shoe.slice()}}
function startRound(input){const s=cloneSession(input);if(s.shoe.length<s.initialShoeSize*(1-s.rules.penetration)||s.shoe.length<25){s.shoe=makeShoe(s.rules.decks,(Number(s.seed)||Date.now())+s.rounds+1);s.initialShoeSize=s.shoe.length;s.runningCount=0;s.cardsSeen=0}const round={dealer:[],hands:[{cards:[],bet:1,done:false,fromSplit:false,splitAces:false,surrendered:false}],active:0,insurance:0,insuranceResolved:true,over:false,net:0,actions:[]};round.hands[0].cards.push(draw(s));round.dealer.push(draw(s));round.hands[0].cards.push(draw(s));round.dealer.push(draw(s));round.insuranceResolved=!(s.rules.insurance&&cardValue(round.dealer[0])===11);if(round.insuranceResolved&&(isBlackjack(round.hands[0])||handValue(round.dealer).total===21))settle(s,round);return{session:s,round}}
function sameSplitValue(a,b){return cardValue(a)===cardValue(b)}function splitCount(r){return r.hands.length-1}
function activeHand(r){return r.hands[r.active]||null}
function legalActions(session,round){if(round.over)return[];if(round.insuranceResolved===false)return['insurance','decline-insurance'];const h=activeHand(round);if(!h||h.done)return[];const v=handValue(h.cards),out=['hit','stand'];if(h.cards.length===2&&( !h.fromSplit||session.rules.doubleAfterSplit))out.push('double');if(h.cards.length===2&&sameSplitValue(h.cards[0],h.cards[1])&&splitCount(round)<session.rules.maxSplits)out.push('split');if(session.rules.surrender&&round.active===0&&round.hands.length===1&&h.cards.length===2&&round.actions.length===0)out.push('surrender');if(v.total>=21)return out.filter(x=>x==='stand'||(x==='split'&&v.total===20));return out}
function advance(session,round){while(round.active<round.hands.length&&round.hands[round.active].done)round.active++;if(round.active>=round.hands.length)dealerPlay(session,round)}
function applyAction(inputSession,inputRound,action){const s=cloneSession(inputSession),r={...inputRound,dealer:inputRound.dealer.slice(),hands:inputRound.hands.map(h=>({...h,cards:h.cards.slice()})),actions:inputRound.actions.slice()};if(!legalActions(s,r).includes(action))throw new Error('Illegal action');if(action==='insurance'||action==='decline-insurance'){r.insurance=action==='insurance'?.5:0;r.insuranceResolved=true;if(handValue(r.dealer).total===21||isBlackjack(r.hands[0]))settle(s,r);return{session:s,round:r}}const h=r.hands[r.active];r.actions.push({hand:r.active,action});if(action==='hit'){h.cards.push(draw(s));const v=handValue(h.cards);if(v.total>=21)h.done=true}else if(action==='stand')h.done=true;else if(action==='double'){h.bet*=2;h.cards.push(draw(s));h.done=true}else if(action==='surrender'){h.surrendered=true;h.done=true}else if(action==='split'){const a=h.cards[0],b=h.cards[1],ace=cardValue(a)===11;const h1={cards:[a,draw(s)],bet:h.bet,done:false,fromSplit:true,splitAces:ace},h2={cards:[b,draw(s)],bet:h.bet,done:false,fromSplit:true,splitAces:ace};if(ace&&!s.rules.hitSplitAces){h1.done=true;h2.done=true}r.hands.splice(r.active,1,h1,h2)}advance(s,r);return{session:s,round:r}}
function dealerPlay(s,r){if(r.over)return;const live=r.hands.some(h=>!h.surrendered&&!handValue(h.cards).bust);if(live){while(true){const v=handValue(r.dealer);if(v.total<17||(v.total===17&&v.soft&&s.rules.dealerHitsSoft17))r.dealer.push(draw(s));else break}}settle(s,r)}
function settle(s,r){if(r.over)return;const dv=handValue(r.dealer),dealerBJ=r.dealer.length===2&&dv.total===21;let net=0;for(const h of r.hands){const hv=handValue(h.cards);let result=0;if(h.surrendered)result=-.5*h.bet;else if(isBlackjack(h)&&!dealerBJ)result=s.rules.blackjackPayout*h.bet;else if(dealerBJ&&!isBlackjack(h))result=-h.bet;else if(hv.bust)result=-h.bet;else if(dv.bust)result=h.bet;else if(hv.total>dv.total)result=h.bet;else if(hv.total<dv.total)result=-h.bet;h.result=result;net+=result}if(r.insurance){net+=dealerBJ?r.insurance*2:-r.insurance}r.net=net;r.over=true;s.score+=net;s.rounds++;if(net>0)s.wins++;else if(net<0)s.losses++;else s.pushes++}
function takeInsurance(inputSession,inputRound){const s=cloneSession(inputSession),r={...inputRound,dealer:inputRound.dealer.slice(),hands:inputRound.hands.map(h=>({...h,cards:h.cards.slice()})),actions:inputRound.actions.slice()};if(!s.rules.insurance||cardValue(r.dealer[0])!==11||r.actions.length||r.insurance)throw new Error('Insurance unavailable');r.insurance=.5;r.insuranceResolved=true;if(handValue(r.dealer).total===21||isBlackjack(r.hands[0]))settle(s,r);return{session:s,round:r}}
function basicStrategy(cards,dealerUp,rules,canSplit,canSurrender){rules=defaultRules(rules);const up=cardValue(dealerUp),v=handValue(cards);if(canSplit&&cards.length===2&&sameSplitValue(cards[0],cards[1])){const x=cardValue(cards[0]);if(x===11||x===8)return'split';if(x===10)return'stand';if(x===9)return[2,3,4,5,6,8,9].includes(up)?'split':'stand';if(x===7)return up<=7?'split':'hit';if(x===6)return up<=6?'split':'hit';if(x===5)return up<=9?'double':'hit';if(x===4)return rules.doubleAfterSplit&&[5,6].includes(up)?'split':'hit';if(x===2||x===3)return up<=7?'split':'hit'}if(canSurrender&&cards.length===2&&!v.soft){if(v.total===16&&[9,10,11].includes(up))return'surrender';if(v.total===15&&up===10)return'surrender'}if(v.soft){if(v.total>=19)return'stand';if(v.total===18)return[3,4,5,6].includes(up)?'double':[2,7,8].includes(up)?'stand':'hit';if(v.total===17)return[3,4,5,6].includes(up)?'double':'hit';if(v.total===15||v.total===16)return[4,5,6].includes(up)?'double':'hit';if(v.total===13||v.total===14)return[5,6].includes(up)?'double':'hit';return'hit'}if(v.total>=17)return'stand';if(v.total>=13)return up<=6?'stand':'hit';if(v.total===12)return[4,5,6].includes(up)?'stand':'hit';if(v.total===11)return up===11&&rules.dealerHitsSoft17?'hit':'double';if(v.total===10)return up<=9?'double':'hit';if(v.total===9)return[3,4,5,6].includes(up)?'double':'hit';return'hit'}
function gradeDecision(session,round,action){const h=activeHand(round);if(!h)return{correct:false,recommended:null};const legal=legalActions(session,round),recommended=basicStrategy(h.cards,round.dealer[0],session.rules,legal.includes('split'),legal.includes('surrender'));return{correct:action===recommended,recommended}}
function trueCount(s){const decksRemaining=Math.max(.25,s.shoe.length/52);return s.runningCount/decksRemaining}
return{makeShoe,cardValue,handValue,isBlackjack,hiLo,defaultRules,createSession,startRound,legalActions,applyAction,dealerPlay,settle,takeInsurance,basicStrategy,gradeDecision,trueCount,sameSplitValue};});
