(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SowstoneEngine=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
const PITS=[[0,1,2,3,4,5],[7,8,9,10,11,12]],STORES=[6,13];
function createGame(options){options=options||{};const stones=Math.max(1,Math.min(8,Number(options.stones)||4));const board=Array(14).fill(stones);board[6]=0;board[13]=0;return{board,current:0,stones,over:false,winner:null,moves:0,last:null};}
function clone(s){return{board:s.board.slice(),current:s.current,stones:s.stones,over:!!s.over,winner:s.winner==null?null:s.winner,moves:s.moves,last:s.last?JSON.parse(JSON.stringify(s.last)):null};}
function sideEmpty(s,p){return PITS[p].every(i=>s.board[i]===0);}function legalMoves(s,p){p=p==null?s.current:p;return s.over?[]:PITS[p].filter(i=>s.board[i]>0);}
function opposite(i){return 12-i;}function ownPit(p,i){return PITS[p].includes(i);}
function finish(s){if(!sideEmpty(s,0)&&!sideEmpty(s,1))return false;for(const p of [0,1]){const rem=PITS[p].reduce((n,i)=>n+s.board[i],0);for(const i of PITS[p])s.board[i]=0;s.board[STORES[p]]+=rem;}s.over=true;s.winner=s.board[6]===s.board[13]?null:(s.board[6]>s.board[13]?0:1);return true;}
function play(input,pit){const s=clone(input);if(s.over)throw new Error('Game over');if(!legalMoves(s).includes(pit))throw new Error('Illegal pit');const p=s.current,skip=STORES[1-p];let stones=s.board[pit];s.board[pit]=0;let i=pit;const path=[];while(stones>0){i=(i+1)%14;if(i===skip)continue;s.board[i]++;stones--;path.push(i);}let captured=0;if(ownPit(p,i)&&i!==STORES[p]&&s.board[i]===1){const opp=opposite(i);if(s.board[opp]>0){captured=s.board[opp]+1;s.board[STORES[p]]+=captured;s.board[i]=0;s.board[opp]=0;}}const extra=i===STORES[p];s.moves++;s.last={player:p,pit,path,last:i,captured,extra};const ended=finish(s);if(!ended&&!extra)s.current=1-p;return{state:s,extraTurn:extra&&!ended,captured,ended};}
function evaluate(s,root){const opp=1-root;let score=(s.board[STORES[root]]-s.board[STORES[opp]])*12;score+=(PITS[root].reduce((n,i)=>n+s.board[i],0)-PITS[opp].reduce((n,i)=>n+s.board[i],0))*1.2;if(s.over){if(s.winner===root)score+=10000;else if(s.winner===opp)score-=10000;}return score;}
function moveFeatures(s,pit){const p=s.current;const r=play(s,pit);let value=(r.state.board[STORES[p]]-s.board[STORES[p]])*10;if(r.extraTurn)value+=24;if(r.captured)value+=r.captured*5;return value;}
function orderMoves(s){return legalMoves(s).slice().sort((a,b)=>moveFeatures(s,b)-moveFeatures(s,a));}
function minimax(s,root,depth,alpha,beta){if(depth<=0||s.over)return evaluate(s,root);const maximizing=s.current===root;let best=maximizing?-Infinity:Infinity;for(const pit of orderMoves(s)){const n=play(s,pit).state;const cost=n.current===s.current?0.55:1;const val=minimax(n,root,depth-cost,alpha,beta);if(maximizing){best=Math.max(best,val);alpha=Math.max(alpha,best);}else{best=Math.min(best,val);beta=Math.min(beta,best);}if(beta<=alpha)break;}return best;}
function botMove(s,difficulty,rng){const moves=legalMoves(s);if(!moves.length)return null;rng=rng||Math.random;if(difficulty==='easy')return moves[Math.floor(rng()*moves.length)];const depth=difficulty==='hard'?7:4,root=s.current;let best=moves[0],bestVal=-Infinity;for(const pit of orderMoves(s)){const n=play(s,pit).state;const val=minimax(n,root,depth-(n.current===s.current?.55:1),-Infinity,Infinity);if(val>bestVal){bestVal=val;best=pit;}}return best;}
function projectedLanding(s,pit){if(!legalMoves(s).includes(pit))return null;const p=s.current,skip=STORES[1-p];let count=s.board[pit],i=pit;while(count--){i=(i+1)%14;if(i===skip){i=(i+1)%14;}}return i;}
return{PITS,STORES,createGame,clone,legalMoves,play,finish,opposite,botMove,evaluate,projectedLanding,sideEmpty};
});
