(()=>{'use strict';const E=window.SowstoneEngine,$=id=>document.getElementById(id),KEY='obg.sowstone.v1';let state,mode='bot',thinking=false;
function save(){try{localStorage.setItem(KEY,JSON.stringify({state,mode,stones:$('stones').value,difficulty:$('difficulty').value,fast:$('fast').checked}));}catch(_e){}}
function restore(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x?.state)return false;state=x.state;mode=x.mode||'bot';$('mode').value=mode;$('stones').value=x.stones||4;$('difficulty').value=x.difficulty||'medium';$('fast').checked=!!x.fast;return true;}catch(_e){return false;}}
function setup(){mode=$('mode').value;state=E.createGame({stones:Number($('stones').value)});thinking=false;render();save();}
function stonesHtml(count){let out='';const shown=Math.min(count,18);for(let i=0;i<shown;i++){const a=(i*137.5)%360,r=10+(i%5)*12,x=50+Math.cos(a*Math.PI/180)*r,y=50+Math.sin(a*Math.PI/180)*r;out+=`<i class="stone" style="left:${x-8}%;top:${y-8}%;transform:rotate(${a}deg)"></i>`;}return out;}
function pitHtml(i,row,col){const count=state.board[i],legal=E.legalMoves(state).includes(i)&&!(mode==='bot'&&state.current===1)&&!thinking;const landing=legal?E.projectedLanding(state,i):null;return`<button class="pit ${legal?'legal':''}" ${legal?'':'disabled'} data-pit="${i}" style="grid-row:${row};grid-column:${col}" aria-label="Pit ${i}, ${count} stones"><span class="count">${count}</span><span class="stones-art">${stonesHtml(count)}</span>${legal&&landing!=null?`<span class="landing">→ ${landing===6||landing===13?'store':landing+1}</span>`:''}</button>`;}
function render(){const b=$('board');let html=`<div class="store p2"><span class="count">${state.board[13]}</span><span class="stones-art">${stonesHtml(state.board[13])}</span></div><div class="store p1"><span class="count">${state.board[6]}</span><span class="stones-art">${stonesHtml(state.board[6])}</span></div>`;for(let n=0;n<6;n++)html+=pitHtml(12-n,1,n+2);for(let n=0;n<6;n++)html+=pitHtml(n,2,n+2);b.innerHTML=html;b.querySelectorAll('.pit.legal').forEach(x=>x.addEventListener('click',()=>humanMove(Number(x.dataset.pit))));$('p2tag').style.display=mode==='bot'?'inline':'none';$('score').textContent=`${state.board[6]} – ${state.board[13]}`;$('turn').textContent=state.over?'Complete':`Player ${state.current+1}${mode==='bot'&&state.current===1?' · Bot':''}`;if(state.last){const L=state.last;$('last').textContent=`P${L.player+1}: pit ${L.pit+1}${L.captured?` · captured ${L.captured}`:''}${L.extra?' · extra turn':''}`;}else $('last').textContent='—';if(state.over)$('status').textContent=state.winner==null?'Tie game.':`Player ${state.winner+1} wins ${state.board[E.STORES[state.winner]]}–${state.board[E.STORES[1-state.winner]]}.`;else $('status').textContent=thinking?'Computer is searching…':'Choose a non-empty pit on your side.';save();}
function humanMove(pit){if(thinking||state.over||(mode==='bot'&&state.current===1))return;apply(pit);}
function apply(pit){let r;try{r=E.play(state,pit)}catch(_e){return}state=r.state;render();if(mode==='bot'&&!state.over&&state.current===1)setTimeout(botTurn,$('fast').checked?60:260);}
function botTurn(){if(state.over||state.current!==1)return;thinking=true;render();setTimeout(()=>{const pit=E.botMove(state,$('difficulty').value);thinking=false;if(pit!=null)apply(pit);},$('fast').checked?25:90);}
$('newGame').addEventListener('click',setup);$('mode').addEventListener('change',setup);$('stones').addEventListener('change',setup);$('difficulty').addEventListener('change',save);$('fast').addEventListener('change',save);if(!restore())setup();else{render();if(mode==='bot'&&!state.over&&state.current===1)setTimeout(botTurn,200);}})();
