(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.FrontiersV2=api;api.mount()}})(typeof globalThis!=='undefined'?globalThis:this,function(){
const MAP={a:{name:'Northwatch',x:14,y:20,adj:['b','e']},b:{name:'Frostgate',x:34,y:16,adj:['a','c','f']},c:{name:'Highmere',x:57,y:21,adj:['b','d','f','g']},d:{name:'Eastreach',x:82,y:17,adj:['c','h']},e:{name:'Westfall',x:17,y:48,adj:['a','f','i']},f:{name:'Greenpass',x:38,y:43,adj:['b','c','e','g','j']},g:{name:'Stonecross',x:62,y:48,adj:['c','f','h','j','k']},h:{name:'Red Coast',x:84,y:44,adj:['d','g','l']},i:{name:'Southbay',x:17,y:77,adj:['e','j']},j:{name:'Lowlands',x:40,y:73,adj:['f','g','i','k']},k:{name:'Sunplain',x:64,y:78,adj:['g','j','l']},l:{name:'Cape Vale',x:85,y:73,adj:['h','k']}};
function clone(s){return{...s,territories:Object.fromEntries(Object.entries(s.territories).map(([k,v])=>[k,{...v}]))}}
function resolveAttack(state,from,to,attackDice,defendDice){const s=clone(state),a=s.territories[from],d=s.territories[to];if(!a||!d||a.owner===d.owner||a.troops<2)return s;const A=[...attackDice].sort((x,y)=>y-x),D=[...defendDice].sort((x,y)=>y-x),pairs=Math.min(A.length,D.length);for(let i=0;i<pairs;i++){if(A[i]>D[i])d.troops--;else a.troops--}if(d.troops<=0){d.owner=a.owner;d.troops=1;a.troops=Math.max(1,a.troops-1)}return s}
function initial(){const territories={};Object.keys(MAP).forEach((k,i)=>territories[k]={owner:i%2===0?'human':'bot',troops:2+(i%3===0?1:0)});return{territories,phase:'reinforce',reinforcements:3,selected:null,turn:'human',winner:null}}
function die(){return 1+Math.floor(Math.random()*6)}
function mount(){if(typeof document==='undefined')return;const map=document.getElementById('map'),status=document.getElementById('status');if(!map)return;let s=initial();
function winCheck(){const owners=new Set(Object.values(s.territories).map(t=>t.owner));if(owners.size===1)s.winner=[...owners][0]}
function render(){document.getElementById('phase').textContent=s.winner?'Finished':s.phase[0].toUpperCase()+s.phase.slice(1);document.getElementById('reinforcements').textContent=s.reinforcements;document.getElementById('selected').textContent=s.selected?MAP[s.selected].name:'None';document.getElementById('phaseTitle').textContent=s.winner?`${s.winner==='human'?'You win':'Computer wins'}`:s.phase[0].toUpperCase()+s.phase.slice(1);document.getElementById('phaseHelp').textContent=s.phase==='reinforce'?'Tap your territory to add troops.':s.phase==='attack'?'Select one of your territories, then an adjacent enemy.':'Select a territory, then an adjacent friendly territory to move one troop.';map.innerHTML=Object.entries(MAP).map(([k,m])=>{const t=s.territories[k];return`<button class="fr-territory ${t.owner}${s.selected===k?' selected':''}" style="--x:${m.x}%;--y:${m.y}%" data-territory="${k}"><small>${m.name}</small><strong>${t.troops}</strong></button>`}).join('');if(s.winner)status.textContent=s.winner==='human'?'All territories secured':'The computer controls the map'}
function click(k){if(s.winner||s.turn!=='human')return;const t=s.territories[k];if(s.phase==='reinforce'){if(t.owner!=='human'||s.reinforcements<=0)return;t.troops++;s.reinforcements--;status.textContent=s.reinforcements?`${s.reinforcements} reinforcements left`:'Ready to attack';if(!s.reinforcements)s.phase='attack'}else if(s.phase==='attack'){if(!s.selected){if(t.owner==='human'&&t.troops>1)s.selected=k}else{const from=s.selected;if(k===from){s.selected=null}else if(MAP[from].adj.includes(k)&&t.owner==='bot'){const a=Math.min(3,s.territories[from].troops-1),d=Math.min(2,t.troops);s=resolveAttack(s,from,k,Array.from({length:a},die),Array.from({length:d},die));s.selected=null;status.textContent='Battle resolved';winCheck()}else if(t.owner==='human'&&t.troops>1)s.selected=k}}else{if(!s.selected){if(t.owner==='human'&&t.troops>1)s.selected=k}else{const from=s.selected;if(MAP[from].adj.includes(k)&&t.owner==='human'){s.territories[from].troops--;t.troops++;endTurn()}s.selected=null}}render()}
function botTurn(){s.turn='bot';status.textContent='Computer is moving';const own=Object.keys(MAP).filter(k=>s.territories[k].owner==='bot');for(let i=0;i<3;i++){const k=own[i%own.length];if(k)s.territories[k].troops++}let attacked=false;for(const from of own){if(s.territories[from].troops<2)continue;const to=MAP[from].adj.find(k=>s.territories[k].owner==='human'&&s.territories[k].troops<=s.territories[from].troops);if(to){const a=Math.min(3,s.territories[from].troops-1),d=Math.min(2,s.territories[to].troops);s=resolveAttack(s,from,to,Array.from({length:a},die),Array.from({length:d},die));attacked=true;break}}winCheck();if(!s.winner){s.turn='human';s.phase='reinforce';s.reinforcements=3;s.selected=null;status.textContent=attacked?'Computer attacked · reinforce your line':'Computer held · reinforce your line'}render()}
function endTurn(){s.selected=null;s.phase='reinforce';s.reinforcements=0;render();setTimeout(botTurn,350)}
document.getElementById('endPhase').addEventListener('click',()=>{if(s.winner)return;if(s.phase==='reinforce'){if(s.reinforcements)return;s.phase='attack'}else if(s.phase==='attack'){s.phase='fortify';s.selected=null;status.textContent='Optional one-troop fortify'}else endTurn();render()});map.addEventListener('click',e=>{const b=e.target.closest('[data-territory]');if(b)click(b.dataset.territory)});document.getElementById('newGame').addEventListener('click',()=>{s=initial();status.textContent='Add 3 troops';render()});render()}
return{MAP,initial,resolveAttack,mount};
});
