(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HeartsEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function seeded(seed){let x=(Number(seed)>>>0)||0x12345678;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}function rank(c){return c%13+2}function suit(c){return Math.floor(c/13)}const CLUBS=0,DIAMONDS=1,HEARTS=2,SPADES=3,QS=SPADES*13+(12-2),TWO_CLUBS=0;
function deck(){return Array.from({length:52},(_,i)=>i)}function shuffle(a,seed){a=a.slice();const r=seeded(seed);for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function sortHand(h){return h.sort((a,b)=>suit(a)-suit(b)||rank(a)-rank(b))}
function passDirection(round){return ['left','right','across','hold'][round%4]}function targetFor(p,dir){if(dir==='left')return(p+1)%4;if(dir==='right')return(p+3)%4;if(dir==='across')return(p+2)%4;return p}
function dealRound(s,seed){const d=shuffle(deck(),seed),hands=Array.from({length:4},()=>[]);d.forEach((c,i)=>hands[i%4].push(c));hands.forEach(sortHand);const dir=passDirection(s.round);return{...s,hands,phase:dir==='hold'?'playing':'passing',passDir:dir,passSelections:Array.from({length:4},()=>null),current:hands.findIndex(h=>h.includes(TWO_CLUBS)),trick:[],taken:Array.from({length:4},()=>[]),heartsBroken:false,roundPoints:[0,0,0,0],history:[],roundOver:false}}
function createGame(o){o=o||{};const base={scores:[0,0,0,0],round:0,target:Math.max(25,Number(o.target)||100),moonMode:o.moonMode==='subtract'?'subtract':'add',over:false,winner:null};return dealRound(base,o.seed==null?Date.now():o.seed)}
function clone(s){return{...s,scores:s.scores.slice(),hands:s.hands.map(h=>h.slice()),passSelections:s.passSelections.map(x=>x&&x.slice()),trick:s.trick.map(x=>({...x})),taken:s.taken.map(h=>h.slice()),roundPoints:s.roundPoints.slice(),history:s.history.map(x=>({...x})),}}
function passCards(input,p,cards){const s=clone(input);if(s.phase!=='passing'||s.passDir==='hold'||!Array.isArray(cards)||cards.length!==3||new Set(cards).size!==3||cards.some(c=>!s.hands[p].includes(c)))throw new Error('Illegal pass');s.passSelections[p]=cards.slice();if(s.passSelections.every(Boolean)){const old=s.hands.map(h=>h.slice());for(let q=0;q<4;q++)for(const c of s.passSelections[q])old[q].splice(old[q].indexOf(c),1);for(let q=0;q<4;q++)old[targetFor(q,s.passDir)].push(...s.passSelections[q]);old.forEach(sortHand);s.hands=old;s.phase='playing';s.current=s.hands.findIndex(h=>h.includes(TWO_CLUBS));s.history.push({type:'passes-complete',direction:s.passDir})}return s}
function trickNumber(s){return s.taken.reduce((n,h)=>n+h.length,0)/4+(s.trick.length?1:0)}
function penalty(c){return suit(c)===HEARTS||c===QS}
function legalCards(s,p){if(s.phase!=='playing'||s.current!==p||s.roundOver||!s.hands[p].length)return[];const hand=s.hands[p],firstTrick=s.taken.every(h=>h.length===0);if(!s.trick.length){if(firstTrick&&hand.includes(TWO_CLUBS))return[TWO_CLUBS];let candidates=hand.slice();if(!s.heartsBroken){const nonHearts=candidates.filter(c=>suit(c)!==HEARTS);if(nonHearts.length)candidates=nonHearts}return candidates}
const lead=suit(s.trick[0].card),follow=hand.filter(c=>suit(c)===lead);let candidates=follow.length?follow:hand.slice();if(firstTrick&&!follow.length){const safe=candidates.filter(c=>!penalty(c));if(safe.length)candidates=safe}return candidates}
function trickWinner(trick){const lead=suit(trick[0].card);let best=trick[0];for(const x of trick.slice(1))if(suit(x.card)===lead&&rank(x.card)>rank(best.card))best=x;return best.player}
function scoreTaken(taken){return taken.reduce((n,c)=>n+(suit(c)===HEARTS?1:c===QS?13:0),0)}
function finishRound(s){let pts=s.taken.map(scoreTaken),moon=pts.findIndex(x=>x===26);if(moon>=0)pts=s.moonMode==='subtract'?pts.map((_,i)=>i===moon?-26:0):pts.map((_,i)=>i===moon?0:26);s.roundPoints=pts;s.scores=s.scores.map((x,i)=>x+pts[i]);s.roundOver=true;s.phase='round-over';if(Math.max(...s.scores)>=s.target){const low=Math.min(...s.scores),leaders=s.scores.map((v,i)=>v===low?i:-1).filter(i=>i>=0);if(leaders.length===1){s.over=true;s.winner=leaders[0];s.phase='game-over'}}return s}
function playCard(input,p,card){const s=clone(input);if(!legalCards(s,p).includes(card))throw new Error('Illegal card');s.hands[p].splice(s.hands[p].indexOf(card),1);s.trick.push({player:p,card});if(suit(card)===HEARTS)s.heartsBroken=true;s.history.push({type:'play',player:p,card});if(s.trick.length===4){const w=trickWinner(s.trick);s.taken[w].push(...s.trick.map(x=>x.card));s.history.push({type:'trick',winner:w,cards:s.trick.map(x=>x.card)});s.trick=[];s.current=w;if(s.hands.every(h=>h.length===0))return finishRound(s)}else s.current=(p+1)%4;return s}
function nextRound(input,seed){if(!input.roundOver||input.over)throw new Error('Round not ready');const base={scores:input.scores.slice(),round:input.round+1,target:input.target,moonMode:input.moonMode,over:false,winner:null};return dealRound(base,seed==null?Date.now():seed)}
function passScore(c){let v=rank(c);if(c===QS)v+=30;if(suit(c)===HEARTS)v+=10;if(rank(c)>=12)v+=5;return v}function botPass(s,p){return s.hands[p].slice().sort((a,b)=>passScore(b)-passScore(a)).slice(0,3)}
function botCard(s,p,difficulty,rng){rng=rng||Math.random;const legal=legalCards(s,p);if(!legal.length)return null;if(difficulty==='easy')return legal[Math.floor(rng()*legal.length)];if(!s.trick.length)return legal.slice().sort((a,b)=>rank(a)-rank(b)+(penalty(a)?15:0)-(penalty(b)?15:0))[0];const lead=suit(s.trick[0].card),currentBest=s.trick.filter(x=>suit(x.card)===lead).sort((a,b)=>rank(b.card)-rank(a.card))[0];const following=legal.filter(c=>suit(c)===lead),voided=following.length===0;if(voided){return legal.slice().sort((a,b)=>(b===QS?100:0)+(suit(b)===HEARTS?rank(b)+20:rank(b)) - ((a===QS?100:0)+(suit(a)===HEARTS?rank(a)+20:rank(a))))[0]}
const under=following.filter(c=>rank(c)<rank(currentBest.card)).sort((a,b)=>rank(b)-rank(a));if(under.length)return under[0];return following.slice().sort((a,b)=>rank(a)-rank(b))[0]}
function playerView(s,p){return{phase:s.phase,current:s.current,hand:s.hands[p].slice(),handCounts:s.hands.map(h=>h.length),scores:s.scores.slice(),round:s.round,passDir:s.passDir,trick:s.trick.map(x=>({...x})),takenCounts:s.taken.map(h=>h.length),heartsBroken:s.heartsBroken,roundOver:s.roundOver,over:s.over,winner:s.winner};}
return{CLUBS,DIAMONDS,HEARTS,SPADES,QS,TWO_CLUBS,rank,suit,seeded,deck,shuffle,passDirection,targetFor,createGame,clone,passCards,legalCards,trickWinner,scoreTaken,finishRound,playCard,nextRound,botPass,botCard,penalty,playerView};});