(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SpadesEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function seeded(seed){let x=(Number(seed)>>>0)||0x87654321;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}function rank(c){return c%13+2}function suit(c){return Math.floor(c/13)}const SPADES=3;function deck(){return Array.from({length:52},(_,i)=>i)}function shuffle(a,seed){a=a.slice();const r=seeded(seed);for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function sortHand(h){return h.sort((a,b)=>suit(a)-suit(b)||rank(a)-rank(b))}
function dealRound(s,seed){const d=shuffle(deck(),seed),hands=Array.from({length:4},()=>[]);d.forEach((c,i)=>hands[i%4].push(c));hands.forEach(sortHand);return{...s,hands,phase:'bidding',current:0,bids:[null,null,null,null],tricks:[0,0,0,0],trick:[],spadesBroken:false,history:[],roundOver:false}}
function createGame(o){o=o||{};const base={teamScores:[0,0],bags:[0,0],round:0,target:Math.max(100,Number(o.target)||500),over:false,winner:null,nilValue:Number(o.nilValue)||100};return dealRound(base,o.seed==null?Date.now():o.seed)}function clone(s){return{...s,teamScores:s.teamScores.slice(),bags:s.bags.slice(),hands:s.hands.map(h=>h.slice()),bids:s.bids.slice(),tricks:s.tricks.slice(),trick:s.trick.map(x=>({...x})),history:s.history.map(x=>({...x}))}}
function bid(input,p,n){const s=clone(input);n=Number(n);if(s.phase!=='bidding'||p!==s.current||s.bids[p]!=null||!Number.isInteger(n)||n<0||n>13)throw new Error('Illegal bid');s.bids[p]=n;s.history.push({type:'bid',player:p,bid:n});if(s.bids.every(x=>x!=null)){s.phase='playing';s.current=0}else s.current=(p+1)%4;return s}
function legalCards(s,p){if(s.phase!=='playing'||s.current!==p||s.roundOver)return[];const hand=s.hands[p];if(!s.trick.length){if(!s.spadesBroken){const non=hand.filter(c=>suit(c)!==SPADES);if(non.length)return non}return hand.slice()}const lead=suit(s.trick[0].card),follow=hand.filter(c=>suit(c)===lead);return follow.length?follow:hand.slice()}
function trickWinner(trick){let best=trick[0];for(const x of trick.slice(1)){const bs=suit(best.card),xs=suit(x.card),lead=suit(trick[0].card);if(xs===SPADES&&bs!==SPADES)best=x;else if(xs===bs&&rank(x.card)>rank(best.card))best=x;else if(bs!==SPADES&&xs===lead&&bs!==lead)best=x}return best.player}
function scoreRound(s){for(let team=0;team<2;team++){const ps=team===0?[0,2]:[1,3],contract=ps.reduce((n,p)=>n+(s.bids[p]||0),0),taken=ps.reduce((n,p)=>n+s.tricks[p],0);let delta=0;for(const p of ps)if(s.bids[p]===0)delta+=s.tricks[p]===0?s.nilValue:-s.nilValue;const made=taken>=contract;if(made){delta+=contract*10;const over=taken-contract;s.bags[team]+=over;delta+=over;while(s.bags[team]>=10){s.bags[team]-=10;delta-=100}}else delta-=contract*10;s.teamScores[team]+=delta}s.roundOver=true;s.phase='round-over';if(Math.max(...s.teamScores)>=s.target||Math.min(...s.teamScores)<=-s.target){if(s.teamScores[0]!==s.teamScores[1]){s.over=true;s.winner=s.teamScores[0]>s.teamScores[1]?0:1;s.phase='game-over'}}return s}
function playCard(input,p,card){const s=clone(input);if(!legalCards(s,p).includes(card))throw new Error('Illegal card');s.hands[p].splice(s.hands[p].indexOf(card),1);s.trick.push({player:p,card});if(suit(card)===SPADES)s.spadesBroken=true;s.history.push({type:'play',player:p,card});if(s.trick.length===4){const w=trickWinner(s.trick);s.tricks[w]++;s.history.push({type:'trick',winner:w});s.trick=[];s.current=w;if(s.hands.every(h=>h.length===0))return scoreRound(s)}else s.current=(p+1)%4;return s}
function nextRound(input,seed){if(!input.roundOver||input.over)throw new Error('Round not ready');return dealRound({teamScores:input.teamScores.slice(),bags:input.bags.slice(),round:input.round+1,target:input.target,over:false,winner:null,nilValue:input.nilValue},seed==null?Date.now():seed)}
function botBid(s,p,difficulty){const h=s.hands[p];let v=0,sp=h.filter(c=>suit(c)===SPADES);v+=sp.filter(c=>rank(c)>=11).length;v+=Math.max(0,sp.length-3)*.65;for(const su of[0,1,2]){const cards=h.filter(c=>suit(c)===su);v+=cards.filter(c=>rank(c)===14).length*.9+cards.filter(c=>rank(c)===13).length*.45;if(cards.length<=2)v+=.3}let b=Math.max(1,Math.min(7,Math.round(v)));if(difficulty==='hard'&&v<.7&&s.teamScores[Math.floor(p%2)]<s.target-100)b=0;return b}
function botCard(s,p,difficulty,rng){rng=rng||Math.random;const legal=legalCards(s,p);if(!legal.length)return null;if(difficulty==='easy')return legal[Math.floor(rng()*legal.length)];const myTeam=p%2,partner=(p+2)%4,teamBid=(s.bids[p]||0)+(s.bids[partner]||0),teamTaken=s.tricks[p]+s.tricks[partner],need=teamTaken<teamBid;const winning=(card)=>trickWinner(s.trick.concat({player:p,card}))===p;if(!s.trick.length){const nonTrump=legal.filter(c=>suit(c)!==SPADES);const pool=nonTrump.length?nonTrump:legal;return pool.slice().sort((a,b)=>need?rank(b)-rank(a):rank(a)-rank(b))[0]}const wins=legal.filter(winning).sort((a,b)=>rank(a)-rank(b));if(need&&wins.length)return wins[0];const loses=legal.filter(c=>!winning(c)).sort((a,b)=>rank(b)-rank(a));if(loses.length)return loses[0];return wins[0]}
function playerView(s,p){return{phase:s.phase,current:s.current,hand:s.hands[p].slice(),handCounts:s.hands.map(h=>h.length),bids:s.bids.slice(),tricks:s.tricks.slice(),trick:s.trick.map(x=>({...x})),teamScores:s.teamScores.slice(),bags:s.bags.slice(),spadesBroken:s.spadesBroken,roundOver:s.roundOver,over:s.over,winner:s.winner};}
return{SPADES,rank,suit,seeded,deck,shuffle,createGame,clone,bid,legalCards,trickWinner,playCard,nextRound,scoreRound,botBid,botCard,playerView};});