(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RacehomeEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function createGame(o){o=o||{};const points=Array(24).fill(0);points[23]=2;points[12]=5;points[7]=3;points[5]=5;points[0]=-2;points[11]=-5;points[16]=-3;points[18]=-5;return{points,bar:[0,0],off:[0,0],current:0,cube:1,cubeOwner:null,matchTarget:Math.max(1,Number(o.matchTarget)||1),matchScore:[0,0],crawford:false,over:false,winner:null,resultValue:0,moves:0,last:null};}
function clone(s){return{...s,points:s.points.slice(),bar:s.bar.slice(),off:s.off.slice(),matchScore:s.matchScore.slice(),last:s.last?JSON.parse(JSON.stringify(s.last)):null}}
function ownCount(s,p,i){const v=s.points[i];return p===0?Math.max(0,v):Math.max(0,-v)}function oppCount(s,p,i){return ownCount(s,1-p,i)}function setOwn(s,p,i,n){const opp=oppCount(s,p,i);if(opp)throw new Error('mixed point');s.points[i]=p===0?n:-n}
function allHome(s,p){if(s.bar[p])return false;for(let i=0;i<24;i++){if(!ownCount(s,p,i))continue;if(p===0&&i>5)return false;if(p===1&&i<18)return false}return true}
function entryPoint(p,die){return p===0?24-die:die-1}function destination(p,from,die){return p===0?from-die:from+die}
function canBearOversize(s,p,from,die){if(!allHome(s,p))return false;const exact=p===0?from+1:24-from;if(die===exact)return true;if(die<exact)return false;if(p===0){for(let i=from+1;i<=5;i++)if(ownCount(s,p,i))return false}else{for(let i=18;i<from;i++)if(ownCount(s,p,i))return false}return true}
function singleMoves(s,die,p){p=p==null?s.current:p;if(s.over)return[];const out=[];if(s.bar[p]>0){const to=entryPoint(p,die);if(oppCount(s,p,to)<2)out.push({from:'bar',to,die,hit:oppCount(s,p,to)===1});return out}for(let from=0;from<24;from++){if(!ownCount(s,p,from))continue;const to=destination(p,from,die);if(to>=0&&to<24){if(oppCount(s,p,to)<2)out.push({from,to,die,hit:oppCount(s,p,to)===1})}else if(canBearOversize(s,p,from,die))out.push({from,to:'off',die,hit:false})}return out}
function applySingle(input,m,p){const s=clone(input);p=p==null?s.current:p;if(m.from==='bar')s.bar[p]--;else setOwn(s,p,m.from,ownCount(s,p,m.from)-1);if(m.to==='off')s.off[p]++;else{if(oppCount(s,p,m.to)===1){setOwn(s,1-p,m.to,0);s.bar[1-p]++}setOwn(s,p,m.to,ownCount(s,p,m.to)+1)}return s}
function keyMove(m){return`${m.from}>${m.to}@${m.die}`}
function turnSequences(s,dice){const p=s.current,expanded=dice[0]===dice[1]?[dice[0],dice[0],dice[0],dice[0]]:dice.slice(),out=[];function rec(st,rem,seq){let progressed=false;for(let k=0;k<rem.length;k++){if(k>0&&rem[k]===rem[k-1])continue;const die=rem[k],moves=singleMoves(st,die,p);for(const m of moves){progressed=true;const next=applySingle(st,m,p),nr=rem.slice();nr.splice(k,1);rec(next,nr,seq.concat(m))}}if(!progressed)out.push(seq)}rec(s,expanded.slice().sort((a,b)=>b-a),[]);let max=Math.max(...out.map(x=>x.length),0),filtered=out.filter(x=>x.length===max);if(dice[0]!==dice[1]&&max===1){const high=Math.max(...filtered.map(x=>x[0]?.die||0));filtered=filtered.filter(x=>(x[0]?.die||0)===high)}const seen=new Set();return filtered.filter(seq=>{const k=seq.map(keyMove).join('|');if(seen.has(k))return false;seen.add(k);return true})}
function pipCount(s,p){let n=s.bar[p]*25;for(let i=0;i<24;i++){const c=ownCount(s,p,i);if(!c)continue;n+=c*(p===0?i+1:24-i)}return n}
function gameValue(s,winner){const loser=1-winner;if(s.off[loser]>0)return 1;const inWinnersHome=winner===0?[0,1,2,3,4,5].some(i=>ownCount(s,loser,i)>0):[18,19,20,21,22,23].some(i=>ownCount(s,loser,i)>0);if(s.bar[loser]>0||inWinnersHome)return 3;return 2}
function applyTurn(input,seq,dice){const legal=turnSequences(input,dice),k=seq.map(keyMove).join('|');if(!legal.some(x=>x.map(keyMove).join('|')===k))throw new Error('Illegal turn sequence');let s=clone(input),p=s.current;for(const m of seq)s=applySingle(s,m,p);s.moves++;s.last={player:p,dice:dice.slice(),sequence:seq.map(x=>({...x}))};if(s.off[p]===15){s.over=true;s.winner=p;s.resultValue=gameValue(s,p)*s.cube;s.matchScore[p]+=s.resultValue}else s.current=1-p;return s}
function canOfferDouble(s,p){return!s.over&&s.current===p&&s.cube<64&&(s.cubeOwner===null||s.cubeOwner===p)&&!s.crawford}
function takeDouble(input,offerer){const s=clone(input);if(!canOfferDouble(s,offerer))throw new Error('Cannot double');s.cube*=2;s.cubeOwner=1-offerer;return s}function passDouble(input,offerer){const s=clone(input);if(!canOfferDouble(s,offerer))throw new Error('Cannot double');s.over=true;s.winner=offerer;s.resultValue=s.cube;s.matchScore[offerer]+=s.cube;return s}
function evaluate(s,root){if(s.over)return s.winner===root?1e6:-1e6;const opp=1-root;let v=(pipCount(s,opp)-pipCount(s,root))*2+(s.off[root]-s.off[opp])*80+(s.bar[opp]-s.bar[root])*45;for(let i=0;i<24;i++){const a=ownCount(s,root,i),b=ownCount(s,opp,i);if(a>=2)v+=8;if(b>=2)v-=8;if(a===1)v-=3;if(b===1)v+=3}return v}
function botSequence(s,dice,difficulty,rng){const seqs=turnSequences(s,dice);if(!seqs.length)return[];rng=rng||Math.random;if(difficulty==='easy')return seqs[Math.floor(rng()*seqs.length)];const root=s.current;let best=seqs[0],bv=-Infinity;for(const seq of seqs){let n=clone(s);for(const m of seq)n=applySingle(n,m,root);let v=evaluate(n,root);if(difficulty==='hard'){const opp=1-root;let ev=0;for(let d1=1;d1<=6;d1++)for(let d2=1;d2<=6;d2++){n.current=opp;const replies=turnSequences(n,[d1,d2]);let worst=Infinity;for(const r of replies){let q=clone(n);for(const m of r)q=applySingle(q,m,opp);worst=Math.min(worst,evaluate(q,root))}ev+=Number.isFinite(worst)?worst:evaluate(n,root)}v=.65*v+.35*(ev/36)}if(v>bv){bv=v;best=seq}}return best}
return{createGame,clone,ownCount,oppCount,allHome,entryPoint,destination,canBearOversize,singleMoves,applySingle,turnSequences,applyTurn,pipCount,gameValue,canOfferDouble,takeDouble,passDouble,evaluate,botSequence,keyMove};});
