(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GridwakeEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
const DEFAULT_FLEET=[{id:'atlas',name:'Atlas',length:5},{id:'comet',name:'Comet',length:4},{id:'lance',name:'Lance',length:3},{id:'echo',name:'Echo',length:3},{id:'skiff',name:'Skiff',length:2}];
function createBoard(size){return{size,ships:[],shots:Array(size*size).fill(0)}}function idx(b,r,c){return r*b.size+c}function rc(b,i){return[Math.floor(i/b.size),i%b.size]}function inside(b,r,c){return r>=0&&c>=0&&r<b.size&&c<b.size}
function cellsFor(b,r,c,length,dir){const cells=[];for(let k=0;k<length;k++){const rr=r+(dir==='v'?k:0),cc=c+(dir==='h'?k:0);if(!inside(b,rr,cc))return null;cells.push(idx(b,rr,cc))}return cells}
function validateFleet(board,fleet){const seen=new Set(),errs=[];const defs=fleet||DEFAULT_FLEET;for(const d of defs){const s=board.ships.find(x=>x.id===d.id);if(!s){errs.push(`missing:${d.id}`);continue}if(s.cells.length!==d.length)errs.push(`length:${d.id}`);for(const c of s.cells){if(c<0||c>=board.size*board.size)errs.push(`bounds:${d.id}`);if(seen.has(c))errs.push(`overlap:${d.id}`);seen.add(c)}}return{valid:errs.length===0,errors:errs}}
function placeShip(input,def,r,c,dir){const b={size:input.size,ships:input.ships.map(s=>({...s,cells:s.cells.slice(),hits:[...(s.hits||[])]})),shots:input.shots.slice()},cells=cellsFor(b,r,c,def.length,dir);if(!cells)throw new Error('Out of bounds');const occupied=new Set(b.ships.flatMap(s=>s.cells));if(cells.some(x=>occupied.has(x)))throw new Error('Overlap');b.ships=b.ships.filter(s=>s.id!==def.id);b.ships.push({id:def.id,name:def.name,length:def.length,cells,hits:[]});return b}
function rng(seed){let x=(Number(seed)>>>0)||0x9e3779b9;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}
function randomFleet(size,fleet,seed){const b=createBoard(size),r=rng(seed==null?Date.now():seed);for(const def of fleet||DEFAULT_FLEET){let ok=false;for(let tries=0;tries<1000&&!ok;tries++){const dir=r()<.5?'h':'v',row=Math.floor(r()*size),col=Math.floor(r()*size);try{const n=placeShip(b,def,row,col,dir);b.ships=n.ships;ok=true}catch(_e){}}if(!ok)throw new Error('Unable to place fleet')}return b}
function fire(input,at){const b={size:input.size,ships:input.ships.map(s=>({...s,cells:s.cells.slice(),hits:[...(s.hits||[])]})),shots:input.shots.slice()};if(at<0||at>=b.shots.length)throw new Error('Bad shot');if(b.shots[at])throw new Error('Repeated shot');const ship=b.ships.find(s=>s.cells.includes(at));if(!ship){b.shots[at]=1;return{board:b,hit:false,sunk:null,win:false}}b.shots[at]=2;if(!ship.hits.includes(at))ship.hits.push(at);const sunk=ship.hits.length===ship.cells.length?ship.id:null,win=b.ships.every(s=>s.hits.length===s.cells.length);return{board:b,hit:true,sunk,win}}
function publicShotView(board){return board.shots.slice()}function canonicalFleet(board){return JSON.stringify(board.ships.slice().sort((a,b)=>a.id.localeCompare(b.id)).map(s=>[s.id,s.cells.slice().sort((a,b)=>a-b)]))}
async function sha256(text){if(typeof crypto!=='undefined'&&crypto.subtle){const data=new TextEncoder().encode(text),buf=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}if(typeof require==='function'){return require('node:crypto').createHash('sha256').update(text).digest('hex')}throw new Error('SHA-256 unavailable')}
async function commitment(board,nonce){return sha256(`${nonce}|${canonicalFleet(board)}`)}async function verifyCommitment(board,nonce,hash){return(await commitment(board,nonce))===hash}
function availableShots(view){return view.map((x,i)=>x===0?i:-1).filter(i=>i>=0)}
function adjacent(size,at){const r=Math.floor(at/size),c=at%size,out=[];for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=r+dr,b=c+dc;if(a>=0&&b>=0&&a<size&&b<size)out.push(a*size+b)}return out}
function probabilityDensity(view,size,lengths){const score=Array(size*size).fill(0),hits=view.map((x,i)=>x===2?i:-1).filter(i=>i>=0);for(const len of lengths){for(const dir of['h','v'])for(let r=0;r<size;r++)for(let c=0;c<size;c++){const cells=[];let ok=true;for(let k=0;k<len;k++){const rr=r+(dir==='v'?k:0),cc=c+(dir==='h'?k:0);if(rr>=size||cc>=size){ok=false;break}const at=rr*size+cc;if(view[at]===1){ok=false;break}cells.push(at)}if(!ok)continue;if(hits.length&&hits.some(h=>!cells.includes(h))){const local=hits.filter(h=>cells.includes(h));if(!local.length)continue}for(const at of cells)if(view[at]===0)score[at]++}}return score}
function botShot(view,size,difficulty,remainingLengths,r){const avail=availableShots(view);if(!avail.length)return null;r=r||Math.random;if(difficulty==='easy')return avail[Math.floor(r()*avail.length)];const hits=view.map((x,i)=>x===2?i:-1).filter(i=>i>=0),target=[];for(const h of hits)for(const n of adjacent(size,h))if(view[n]===0&&!target.includes(n))target.push(n);if(difficulty==='medium'&&target.length)return target[Math.floor(r()*target.length)];const density=probabilityDensity(view,size,remainingLengths||DEFAULT_FLEET.map(x=>x.length)),pool=target.length?target:avail;let best=pool[0],bv=-1;for(const at of pool){const parity=((Math.floor(at/size)+at%size)&1)===0?0.25:0;const v=density[at]+parity;if(v>bv){bv=v;best=at}}return best}
return{DEFAULT_FLEET,createBoard,idx,rc,cellsFor,validateFleet,placeShip,randomFleet,fire,publicShotView,canonicalFleet,commitment,verifyCommitment,availableShots,probabilityDensity,botShot};});
