export const regions=[['Aurora Reach',4],['Ember Coast',3],['Verdant Crown',4],['Ironwild',5],['Sunscar',3],['Mist Isles',3]];
const names=['Frostgate','Northwatch','Glassmere','Auric Bay','Cinderfall','Redhaven','Ashport','Brass Cape','Mossheart','Greenveil','Thornfield','Rivermeet','Oakspire','Deepwood','Stonewake','Ironpass','Blackridge','Highforge','Slateford','Wolfmarch','Dunewell','Saffron','Solspire','Brightwash','Cloudrest','Fogbank','Starling','Moonkey','Rainholm','Gullrock','Windward','Stormrest','Seabreak','Farpoint','Dawnreef','Nightreef'];
const centers=[[115,105],[205,75],[285,120],[170,160],[390,125],[470,95],[535,145],[445,185],[270,235],[350,215],[315,285],[405,270],[235,315],[475,325],[590,245],[665,210],[715,275],[625,320],[690,370],[560,385],[180,410],[270,390],[350,430],[255,480],[465,455],[545,465],[625,485],[705,455],[760,415],[805,345],[775,250],[820,180],[735,135],[650,105],[570,65],[355,65]];
export const territories=names.map((name,i)=>({id:i,name,region:Math.floor(i/6),x:centers[i][0],y:centers[i][1],adj:[(i+35)%36,(i+1)%36,(i+6)%36,(i+30)%36]}));
// Add local mesh links while keeping adjacency symmetric.
for(let i=0;i<36;i++) for(const j of [...territories[i].adj]) if(!territories[j].adj.includes(i)) territories[j].adj.push(i);
export function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function reinforcement(state,p){const owned=state.territories.filter(t=>t.owner===p).length;let n=Math.max(3,Math.floor(owned/3));regions.forEach((r,ri)=>{if(state.territories.filter(t=>t.region===ri).every(t=>t.owner===p))n+=r[1]});return n}
export function resolveCombat(a,d,rng=Math.random){let al=0,dl=0;const ar=Array.from({length:Math.min(3,a)},()=>1+Math.floor(rng()*6)).sort((x,y)=>y-x);const dr=Array.from({length:Math.min(2,d)},()=>1+Math.floor(rng()*6)).sort((x,y)=>y-x);for(let i=0;i<Math.min(ar.length,dr.length);i++) ar[i]>dr[i]?dl++:al++;return{attackerLoss:al,defenderLoss:dl,ar,dr}}
export function redeemValue(n){return [4,6,8,10,12,15][n]??15+(n-5)*5}
export function score(state,p){return state.territories.filter(t=>t.owner===p).reduce((s,t)=>s+1+t.armies*.12,s,0)}
export function winner(state,mode='domination'){const alive=[...new Set(state.territories.map(t=>t.owner))];if(mode==='domination'&&alive.length===1)return alive[0];if(mode==='capital'){for(const p of state.players){const caps=state.players.filter(x=>x.capital!=null).map(x=>x.capital);if(caps.every(c=>state.territories[c].owner===p.id))return p.id}}return null}
export function newGame(count=4,seed=42){const rng=mulberry32(seed);const players=Array.from({length:count},(_,i)=>({id:i,name:i?'Bot '+i:'You',bot:i?['easy','medium','hard'][Math.min(i-1,2)]:null,cards:[],capital:null}));const ts=territories.map((t,i)=>({...t,owner:i%count,armies:1}));for(let i=ts.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[ts[i].owner,ts[j].owner]=[ts[j].owner,ts[i].owner]};players.forEach(p=>p.capital=ts.find(t=>t.owner===p.id).id);return{players,territories:ts,turn:0,phase:'reinforce',reinforcements:reinforcement({territories:ts},0),history:['The frontier has opened.'],conquered:false,sets:0,round:1}}
export function botTarget(state,p){const mine=state.territories.filter(t=>t.owner===p&&t.armies>1);let opts=[];mine.forEach(a=>a.adj.forEach(id=>{const d=state.territories[id];if(d.owner!==p)opts.push({a,d,v:a.armies-d.armies+(state.players[p].bot==='hard'?(5-d.armies+(regions[d.region]?.[1]||0)):Math.random())})}));return opts.sort((x,y)=>y.v-x.v)[0]}
