(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MillstoneEngine=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
const EDGES=[[0,1],[1,2],[0,9],[2,14],[3,4],[4,5],[3,10],[5,13],[6,7],[7,8],[6,11],[8,12],[9,10],[10,11],[11,15],[9,21],[12,13],[13,14],[12,17],[14,23],[15,16],[16,17],[15,18],[17,20],[18,19],[19,20],[18,21],[20,23],[21,22],[22,23]];
const MILLS=[[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23],[0,9,21],[3,10,18],[6,11,15],[1,4,7],[16,19,22],[8,12,17],[5,13,20],[2,14,23]];
const ADJ=Array.from({length:24},()=>[]);for(const [a,b] of EDGES){ADJ[a].push(b);ADJ[b].push(a)}
function clone(s){return{board:s.board.slice(),current:s.current,reserves:s.reserves.slice(),pendingRemoval:!!s.pendingRemoval,over:!!s.over,winner:s.winner,fly:s.fly!==false,moves:s.moves,drawByRepetition:!!s.drawByRepetition,hashCounts:{...(s.hashCounts||{})},last:s.last?{...s.last}:null};}
function createGame(options){options=options||{};const s={board:Array(24).fill(-1),current:0,reserves:[9,9],pendingRemoval:false,over:false,winner:null,fly:options.fly!==false,moves:0,drawByRepetition:options.drawByRepetition!==false,hashCounts:{},last:null};record(s);return s;}
function countPieces(s,p){return s.board.filter(x=>x===p).length}
function phase(s,p){if(s.reserves[p]>0)return'placing';return s.fly&&countPieces(s,p)===3?'flying':'moving'}
function isMill(s,p,pos){return MILLS.some(m=>m.includes(pos)&&m.every(i=>s.board[i]===p))}
function allPiecesInMills(s,p){const ps=s.board.map((x,i)=>x===p?i:-1).filter(i=>i>=0);return ps.length>0&&ps.every(i=>isMill(s,p,i))}
function removalTargets(s){if(!s.pendingRemoval)return[];const opp=1-s.current;const pieces=s.board.map((x,i)=>x===opp?i:-1).filter(i=>i>=0);const outside=pieces.filter(i=>!isMill(s,opp,i));return outside.length?outside:pieces}
function legalActions(s){if(s.over)return[];if(s.pendingRemoval)return removalTargets(s).map(at=>({type:'remove',at}));const p=s.current,ph=phase(s,p);if(ph==='placing')return s.board.map((x,i)=>x===-1?{type:'place',to:i}:null).filter(Boolean);const origins=s.board.map((x,i)=>x===p?i:-1).filter(i=>i>=0),out=[];for(const from of origins){const tos=ph==='flying'?s.board.map((x,i)=>x===-1?i:-1).filter(i=>i>=0):ADJ[from].filter(i=>s.board[i]===-1);for(const to of tos)out.push({type:'move',from,to})}return out}
function stateHash(s){return `${s.current}|${s.reserves.join(',')}|${s.pendingRemoval?1:0}|${s.board.join('')}`}
function record(s){if(!s.drawByRepetition||s.pendingRemoval)return;const h=stateHash(s);s.hashCounts[h]=(s.hashCounts[h]||0)+1;if(s.hashCounts[h]>=3){s.over=true;s.winner=null}}
function checkLoss(s){if(s.reserves[0]||s.reserves[1])return;for(const p of[0,1]){if(countPieces(s,p)<3){s.over=true;s.winner=1-p;return}if(!s.pendingRemoval&&s.current===p&&legalActions(s).length===0){s.over=true;s.winner=1-p;return}}}
function apply(input,a){const s=clone(input);if(s.over)throw new Error('Game over');const legal=legalActions(s).some(x=>x.type===a.type&&x.to===a.to&&x.from===a.from&&x.at===a.at);if(!legal)throw new Error('Illegal action');const p=s.current;if(a.type==='place'){s.board[a.to]=p;s.reserves[p]--;s.moves++;s.last={...a,player:p};if(isMill(s,p,a.to))s.pendingRemoval=true;else{s.current=1-p;checkLoss(s);record(s)}}else if(a.type==='move'){s.board[a.from]=-1;s.board[a.to]=p;s.moves++;s.last={...a,player:p};if(isMill(s,p,a.to))s.pendingRemoval=true;else{s.current=1-p;checkLoss(s);record(s)}}else{s.board[a.at]=-1;s.pendingRemoval=false;s.last={...a,player:p};s.current=1-p;checkLoss(s);if(!s.over)record(s)}return s}
function millsCount(s,p){return MILLS.reduce((n,m)=>n+(m.every(i=>s.board[i]===p)?1:0),0)}
function potentialMills(s,p){let n=0;for(const m of MILLS){const vals=m.map(i=>s.board[i]);if(vals.filter(x=>x===p).length===2&&vals.includes(-1))n++}return n}
function mobility(s,p){if(s.reserves[p]>0)return s.board.filter(x=>x===-1).length;const ph=phase(s,p),orig=s.board.map((x,i)=>x===p?i:-1).filter(i=>i>=0);if(ph==='flying')return orig.length*s.board.filter(x=>x===-1).length;return orig.reduce((n,i)=>n+ADJ[i].filter(j=>s.board[j]===-1).length,0)}
function evaluate(s,root){if(s.over){if(s.winner===root)return 1e6;if(s.winner===1-root)return-1e6;return 0}const opp=1-root;return(countPieces(s,root)-countPieces(s,opp))*110+(millsCount(s,root)-millsCount(s,opp))*70+(potentialMills(s,root)-potentialMills(s,opp))*22+(mobility(s,root)-mobility(s,opp))*2+(s.reserves[opp]-s.reserves[root])*3}
function actionScore(s,a){const p=s.current;if(a.type==='remove')return isMill(s,1-p,a.at)?40:80;let n=apply(s,a),v=0;if(n.pendingRemoval)v+=120;if(a.type==='move'){const before=potentialMills(s,p),after=potentialMills(n,p);v+=(after-before)*18}return v}
function ordered(s){return legalActions(s).slice().sort((a,b)=>actionScore(s,b)-actionScore(s,a))}
function minimax(s,root,depth,alpha,beta){if(depth<=0||s.over)return evaluate(s,root);const maximizing=s.current===root;let best=maximizing?-Infinity:Infinity;for(const a of ordered(s)){const n=apply(s,a);const cost=n.current===s.current?0.35:1;const v=minimax(n,root,depth-cost,alpha,beta);if(maximizing){best=Math.max(best,v);alpha=Math.max(alpha,best)}else{best=Math.min(best,v);beta=Math.min(beta,best)}if(beta<=alpha)break}return best}
function botAction(s,difficulty,rng){const acts=legalActions(s);if(!acts.length)return null;rng=rng||Math.random;if(difficulty==='easy')return acts[Math.floor(rng()*acts.length)];if(difficulty==='medium')return ordered(s)[0];const root=s.current,depth=phase(s,root)==='placing'?2.8:3.5;let best=acts[0],val=-Infinity;for(const a of ordered(s)){const n=apply(s,a),v=minimax(n,root,depth-(n.current===s.current?0.35:1),-Infinity,Infinity);if(v>val){val=v;best=a}}return best}
return{EDGES,MILLS,ADJ,createGame,clone,countPieces,phase,isMill,removalTargets,legalActions,apply,evaluate,botAction,stateHash};
});
