(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GinRummyEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function seeded(seed){let x=(Number(seed)>>>0)||0x31415926;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}function rank(c){return c%13+1}function suit(c){return Math.floor(c/13)}function point(c){return Math.min(10,rank(c))}function deck(){return Array.from({length:52},(_,i)=>i)}function shuffle(a,seed){a=a.slice();const r=seeded(seed);for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function sortHand(h){return h.sort((a,b)=>suit(a)-suit(b)||rank(a)-rank(b))}
function meldMasks(hand){const out=[];for(let r=1;r<=13;r++){const ids=hand.map((c,i)=>rank(c)===r?i:-1).filter(i=>i>=0);if(ids.length>=3){for(let mask=1;mask<(1<<ids.length);mask++){const sel=ids.filter((_,k)=>mask>>k&1);if(sel.length>=3)out.push(sel.reduce((m,i)=>m|(1<<i),0))}}}for(let su=0;su<4;su++){const ids=hand.map((c,i)=>suit(c)===su?i:-1).filter(i=>i>=0).sort((a,b)=>rank(hand[a])-rank(hand[b]));for(let a=0;a<ids.length;a++){for(let b=a+2;b<ids.length;b++){const seq=ids.slice(a,b+1),rs=seq.map(i=>rank(hand[i]));if(rs.every((r,k)=>k===0||r===rs[k-1]+1))out.push(seq.reduce((m,i)=>m|(1<<i),0));else if(rs.at(-1)-rs[0]>seq.length-1)break}}}return[...new Set(out)]}
function optimalMelds(hand){const masks=meldMasks(hand),memo=new Map();function rec(used){if(memo.has(used))return memo.get(used);let best={covered:0,masks:[]};for(const m of masks){if(m&used)continue;const cards=hand.filter((_,i)=>m>>i&1),v=cards.reduce((n,c)=>n+point(c),0),tail=rec(used|m),cand={covered:v+tail.covered,masks:[m,...tail.masks]};if(cand.covered>best.covered)best=cand}memo.set(used,best);return best}const best=rec(0),used=best.masks.reduce((a,m)=>a|m,0),melds=best.masks.map(m=>hand.filter((_,i)=>m>>i&1)),deadwood=hand.filter((_,i)=>!(used>>i&1));return{melds,deadwood,deadwoodValue:deadwood.reduce((n,c)=>n+point(c),0)}}
function createGame(o){o=o||{};const d=shuffle(deck(),o.seed==null?Date.now():o.seed),hands=[sortHand(d.splice(0,10)),sortHand(d.splice(0,10))],discard=[d.pop()];return{hands,stock:d,discard,current:0,phase:'draw',drawnFromDiscard:null,scores:[0,0],target:Math.max(25,Number(o.target)||100),round:0,over:false,winner:null,history:[]}}
function clone(s){return{...s,hands:s.hands.map(h=>h.slice()),stock:s.stock.slice(),discard:s.discard.slice(),scores:s.scores.slice(),history:s.history.map(x=>({...x}))}}
function finishStockDraw(s){s.phase='round-over';s.roundResult={winner:null,points:0,type:'stock-draw'};s.history.push({type:'round',winner:null,points:0,resultType:'stock-draw'});return s}
function drawStock(input){const s=clone(input);if(s.over||s.phase!=='draw')throw new Error('Cannot draw');if(s.stock.length<=2)return finishStockDraw(s);const c=s.stock.pop();if(c==null)return finishStockDraw(s);s.hands[s.current].push(c);sortHand(s.hands[s.current]);s.phase='discard';s.drawnFromDiscard=null;s.history.push({type:'draw-stock',player:s.current});return s}
function drawDiscard(input){const s=clone(input);if(s.over||s.phase!=='draw'||!s.discard.length)throw new Error('Cannot draw discard');const c=s.discard.pop();s.hands[s.current].push(c);sortHand(s.hands[s.current]);s.phase='discard';s.drawnFromDiscard=c;s.history.push({type:'draw-discard',player:s.current,card:c});return s}
function canKnockHand(hand){return optimalMelds(hand).deadwoodValue<=10}
function layoffDeadwood(deadwood,knockerMelds){let remaining=deadwood.slice(),melds=knockerMelds.map(m=>m.slice()),changed=true;while(changed){changed=false;outer:for(let i=0;i<remaining.length;i++){const c=remaining[i];for(const m of melds){const sameRank=m.every(x=>rank(x)===rank(m[0]));if(sameRank&&m.length<4&&rank(c)===rank(m[0])){m.push(c);remaining.splice(i,1);changed=true;break outer}const sameSuit=m.every(x=>suit(x)===suit(m[0]));if(sameSuit){const rs=m.map(rank).sort((a,b)=>a-b);if(suit(c)===suit(m[0])&&(rank(c)===rs[0]-1||rank(c)===rs.at(-1)+1)){m.push(c);remaining.splice(i,1);changed=true;break outer}}}}}return remaining}
function scoreKnock(s,knocker){const opp=1-knocker,km=optimalMelds(s.hands[knocker]),om=optimalMelds(s.hands[opp]);if(km.deadwoodValue===0){const pts=25+om.deadwoodValue;s.scores[knocker]+=pts;return{winner:knocker,points:pts,type:'gin',knockerDeadwood:0,opponentDeadwood:om.deadwoodValue}}
const laid=layoffDeadwood(om.deadwood,km.melds),ov=laid.reduce((n,c)=>n+point(c),0),kv=km.deadwoodValue;if(ov<=kv){const pts=25+kv-ov;s.scores[opp]+=pts;return{winner:opp,points:pts,type:'undercut',knockerDeadwood:kv,opponentDeadwood:ov}}const pts=ov-kv;s.scores[knocker]+=pts;return{winner:knocker,points:pts,type:'knock',knockerDeadwood:kv,opponentDeadwood:ov}}
function finishRound(s,knocker){const result=scoreKnock(s,knocker);s.phase='round-over';s.roundResult=result;s.history.push({type:'round',resultType:result.type,winner:result.winner,points:result.points});if(Math.max(...s.scores)>=s.target){s.over=true;s.winner=s.scores[0]===s.scores[1]?null:(s.scores[0]>s.scores[1]?0:1);s.phase='game-over'}return s}
function discardCard(input,card,knock){const s=clone(input),p=s.current;if(s.over||s.phase!=='discard'||!s.hands[p].includes(card)||card===s.drawnFromDiscard)throw new Error('Illegal discard');s.hands[p].splice(s.hands[p].indexOf(card),1);s.discard.push(card);s.history.push({type:'discard',player:p,card});if(knock){if(!canKnockHand(s.hands[p]))throw new Error('Deadwood exceeds 10');return finishRound(s,p)}if(s.stock.length<=2)return finishStockDraw(s);s.current=1-p;s.phase='draw';s.drawnFromDiscard=null;return s}
function nextRound(input,seed){if(input.phase!=='round-over'||input.over)throw new Error('Round not ready');const n=createGame({seed:seed==null?Date.now():seed,target:input.target});n.scores=input.scores.slice();n.round=input.round+1;return n}
function bestDiscard(hand,forbidden){let best=null,bv=Infinity;for(const c of hand){if(c===forbidden)continue;const h=hand.slice();h.splice(h.indexOf(c),1);const v=optimalMelds(h).deadwoodValue;if(v<bv||(v===bv&&point(c)>point(best??c))){bv=v;best=c}}return{card:best,deadwood:bv}}
function botTurnChoice(s,difficulty){const p=s.current,top=s.discard.at(-1),stockHand=s.hands[p].slice(),withDiscard=stockHand.concat(top),discardPlan=bestDiscard(withDiscard,top),current=optimalMelds(stockHand).deadwoodValue;const take=top!=null&&discardPlan.deadwood<current-(difficulty==='easy'?2:0);return{draw:take?'discard':'stock'}}
function botDiscard(s,difficulty){const p=s.current,plan=bestDiscard(s.hands[p],s.drawnFromDiscard);const h=s.hands[p].slice();h.splice(h.indexOf(plan.card),1);const dead=optimalMelds(h).deadwoodValue;return{card:plan.card,knock:dead===0||(difficulty==='hard'?dead<=7:dead<=3)}}
function playerView(s,p){return{current:s.current,phase:s.phase,hand:s.hands[p].slice(),opponentCount:s.hands[1-p].length,stockCount:s.stock.length,discard:s.discard.slice(),scores:s.scores.slice(),target:s.target,round:s.round,roundResult:s.roundResult?{...s.roundResult}:null,over:s.over,winner:s.winner};}
return{rank,suit,point,deck,shuffle,createGame,clone,meldMasks,optimalMelds,finishStockDraw,drawStock,drawDiscard,discardCard,canKnockHand,layoffDeadwood,scoreKnock,nextRound,bestDiscard,botTurnChoice,botDiscard,playerView};});