(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SparkSixEngine=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
const DEFAULT_RULES={straight:true,threePairs:true,straightScore:1500,threePairsScore:1500,singleOne:100,singleFive:50,nKindMultiplier:{3:1,4:2,5:3,6:4}};
function counts(dice){const c=Array(7).fill(0);for(const d of dice)c[d]++;return c;}
function tripleBase(face,rules){return face===1?1000:face*100;}
function scoreSelection(dice,rules){rules={...DEFAULT_RULES,...(rules||{}),nKindMultiplier:{...DEFAULT_RULES.nKindMultiplier,...((rules||{}).nKindMultiplier||{})}};if(!Array.isArray(dice)||!dice.length)return{valid:false,score:0,kind:'none'};const c=counts(dice);if(dice.length===6&&rules.straight&&[1,2,3,4,5,6].every(f=>c[f]===1))return{valid:true,score:rules.straightScore,kind:'straight'};if(dice.length===6&&rules.threePairs&&c.slice(1).filter(n=>n===2).length===3)return{valid:true,score:rules.threePairsScore,kind:'three-pairs'};let score=0;const parts=[];for(let f=1;f<=6;f++){const n=c[f];if(!n)continue;if(n>=3){const mult=rules.nKindMultiplier[n]||n-2;const pts=tripleBase(f,rules)*mult;score+=pts;parts.push(`${n}×${f}`);continue;}if(f===1){score+=n*rules.singleOne;parts.push(`${n} one${n>1?'s':''}`);continue;}if(f===5){score+=n*rules.singleFive;parts.push(`${n} five${n>1?'s':''}`);continue;}return{valid:false,score:0,kind:'invalid'};}return{valid:score>0,score,kind:parts.join(' + ')};}
function scoringMask(dice,rules){const c=counts(dice);if(dice.length===6){const full=scoreSelection(dice,rules);if(full.valid&&(full.kind==='straight'||full.kind==='three-pairs'))return dice.map(()=>true);}return dice.map(d=>d===1||d===5||c[d]>=3);}
function isBust(dice,rules){return !scoringMask(dice,rules).some(Boolean);}
function bestSelection(dice,rules){let best={indices:[],score:0,kind:'none'};const n=dice.length;for(let mask=1;mask<(1<<n);mask++){const values=[],indices=[];for(let i=0;i<n;i++)if(mask&(1<<i)){values.push(dice[i]);indices.push(i);}const s=scoreSelection(values,rules);if(!s.valid)continue;const utility=s.score+(indices.length===n?250:0)+indices.length*2;if(utility>best.score+(best.indices.length===n?250:0)+best.indices.length*2)best={indices,score:s.score,kind:s.kind};}return best;}
const bustCache=new Map();function bustProbability(n,rules){const key=`${n}:${JSON.stringify(rules||{})}`;if(bustCache.has(key))return bustCache.get(key);let total=0,busts=0,dice=Array(n).fill(1);function rec(i){if(i===n){total++;if(isBust(dice,rules))busts++;return;}for(let d=1;d<=6;d++){dice[i]=d;rec(i+1);}}rec(0);const p=busts/total;bustCache.set(key,p);return p;}
function botDecision(context,rules){const p=bustProbability(context.diceRemaining||6,rules);const lead=(context.myScore||0)-(context.bestOpponent||0);const need=Math.max(0,(context.target||10000)-(context.myScore||0));const threshold=need<=1200?Math.max(250,need):lead<-1500?350:lead>1500?700:500;const riskCost=(context.turnScore||0)*p;return (context.turnScore||0)>=threshold||riskCost>230?'bank':'roll';}
function createMatch(options){options=options||{};const players=Math.max(1,Math.min(4,Number(options.players)||2));return{scores:Array(players).fill(0),players,current:0,target:Math.max(1000,Number(options.target)||10000),finalTrigger:null,finalRemaining:0,over:false,winner:null,turns:0};}
function cloneMatch(m){return{scores:m.scores.slice(),players:m.players,current:m.current,target:m.target,finalTrigger:m.finalTrigger,finalRemaining:m.finalRemaining,over:!!m.over,winner:m.winner,turns:m.turns};}
function endTurn(input,turnScore){const m=cloneMatch(input);if(m.over)throw new Error('Match over');const p=m.current;m.scores[p]+=Math.max(0,Number(turnScore)||0);m.turns++;if(m.finalTrigger===null&&m.scores[p]>=m.target){m.finalTrigger=p;m.finalRemaining=m.players-1;if(m.players===1)m.finalRemaining=0;}else if(m.finalTrigger!==null&&p!==m.finalTrigger){m.finalRemaining=Math.max(0,m.finalRemaining-1);}if(m.finalTrigger!==null&&m.finalRemaining===0){m.over=true;const high=Math.max(...m.scores),wins=m.scores.map((s,i)=>s===high?i:null).filter(i=>i!==null);m.winner=wins.length===1?wins[0]:null;return m;}m.current=(p+1)%m.players;return m;}
return{DEFAULT_RULES,scoreSelection,scoringMask,isBust,bestSelection,bustProbability,botDecision,createMatch,endTurn,cloneMatch};
});
