(()=>{'use strict';const E=window.SparkSixEngine,$=id=>document.getElementById(id),KEY='obg.spark-six.v1';let match=null,mode='bot',rolled=[],selected=new Set(),turnScore=0,diceRemaining=6,rolling=false;
const pipMap={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
function playersForMode(){return mode==='solo'?1:mode==='local3'?3:mode==='local4'?4:2;}
function setup(){mode=$('mode').value;match=E.createMatch({players:playersForMode(),target:Number($('target').value)});resetTurn();render();save();if(isBotTurn())setTimeout(botPlay,300);}
function resetTurn(){rolled=[];selected=new Set();turnScore=0;diceRemaining=6;rolling=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify({match,mode,rolled,selected:[...selected],turnScore,diceRemaining,target:$('target').value,difficulty:$('difficulty').value}));}catch(_e){}}
function restore(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x?.match)return false;match=x.match;mode=x.mode||'bot';rolled=x.rolled||[];selected=new Set(x.selected||[]);turnScore=x.turnScore||0;diceRemaining=x.diceRemaining||6;$('mode').value=mode;$('target').value=x.target||10000;$('difficulty').value=x.difficulty||'balanced';return true;}catch(_e){return false;}}
function isBotTurn(){return mode==='bot'&&!match.over&&match.current===1;}
function randomDie(){return 1+Math.floor(Math.random()*6)}function rollDice(){if(match.over||rolling||isBotTurn())return;if(rolled.length&&selected.size)return setStatus('Keep or bank the selected scoring dice first.');rolled=Array.from({length:diceRemaining},randomDie);selected=new Set();if(E.isBust(rolled)){render();setStatus('Bust — no scoring dice. Turn score is lost.');setTimeout(()=>finishTurn(0),700);return;}render();setStatus('Select a valid scoring die or group.');}
function selectedValues(){return [...selected].sort((a,b)=>a-b).map(i=>rolled[i]);}function selectionScore(){return E.scoreSelection(selectedValues());}
function toggle(i){if(match.over||isBotTurn())return;if(selected.has(i))selected.delete(i);else selected.add(i);render();}
function commit(){const s=selectionScore();if(!s.valid)return null;turnScore+=s.score;diceRemaining-=selected.size;rolled=[];selected=new Set();if(diceRemaining===0){diceRemaining=6;setStatus('Hot dice — all six are live again.');}return s;}
function keepRoll(){if(match.over||isBotTurn())return;const s=commit();if(!s)return setStatus('Selection must contain only scoring dice/groups.');render();setTimeout(rollDice,120);}
function bank(){if(match.over||isBotTurn())return;if(rolled.length){const s=commit();if(!s)return setStatus('Choose a valid scoring selection before banking.');}if(turnScore<=0)return setStatus('Score something before banking.');finishTurn(turnScore);}
function finishTurn(score){match=E.endTurn(match,score);resetTurn();render();if(match.over){const high=Math.max(...match.scores);setStatus(match.winner==null?`Match ends tied at ${high}.`:`Player ${match.winner+1} wins with ${match.scores[match.winner].toLocaleString()}.`);return;}setStatus(match.finalTrigger!=null?`Final round: ${match.finalRemaining} player turn${match.finalRemaining===1?'':'s'} remain.`:'Next turn.');save();if(isBotTurn())setTimeout(botPlay,350);}
function chooseBotSelection(){return E.bestSelection(rolled);}
function botPlay(){if(!isBotTurn()||match.over)return;rolled=Array.from({length:diceRemaining},randomDie);selected=new Set();render();setStatus('Computer rolled…');setTimeout(()=>{if(E.isBust(rolled)){setStatus('Computer busts.');setTimeout(()=>finishTurn(0),420);return;}const best=chooseBotSelection();selected=new Set(best.indices);render();setTimeout(()=>{commit();render();const diff=$('difficulty').value;let decision=E.botDecision({turnScore,diceRemaining,myScore:match.scores[1],bestOpponent:Math.max(...match.scores.filter((_,i)=>i!==1)),target:match.target});if(diff==='safe'&&turnScore>=300)decision='bank';if(diff==='bold'&&turnScore<850)decision='roll';if(decision==='bank'){setStatus(`Computer banks ${turnScore}.`);setTimeout(()=>finishTurn(turnScore),380);}else{setStatus('Computer presses its luck.');setTimeout(botPlay,430);}},300);},350);}
function dieHtml(v,i){const pips=Array.from({length:9},(_,n)=>pipMap[v].includes(n)?'<i class="pip"></i>':'<i></i>').join('');return`<button class="die ${selected.has(i)?'selected':''}" data-i="${i}" aria-label="Die ${i+1}: ${v}${selected.has(i)?', selected':''}">${pips}</button>`;}
function render(){const score=selectionScore();$('dice').innerHTML=rolled.length?rolled.map(dieHtml).join(''):`<div style="grid-column:1/-1;text-align:center;color:#65738a">${isBotTurn()?'Computer turn':'Roll '+diceRemaining+' dice'}</div>`;$('dice').querySelectorAll('.die').forEach(d=>d.addEventListener('click',()=>toggle(Number(d.dataset.i))));$('turnScore').textContent=turnScore.toLocaleString();$('projected').textContent=(turnScore+(score.valid?score.score:0)).toLocaleString();$('scoreboard').innerHTML=Array.from({length:4},(_,i)=>`<div class="score-item ${i===match.current&&!match.over?'active':''}" style="${i>=match.players?'display:none':''}"><span>Player ${i+1}${mode==='bot'&&i===1?' · Bot':''}</span><strong>${i<match.players?match.scores[i].toLocaleString():'—'}</strong></div>`).join('');const human=!isBotTurn()&&!match.over;$('roll').disabled=!human||rolled.length>0;$('keepRoll').disabled=!human||!rolled.length||!score.valid;$('bank').disabled=!human||((!rolled.length&&turnScore<=0)||(rolled.length&&!score.valid));save();}
function setStatus(t){$('status').textContent=t;save();}
$('roll').addEventListener('click',rollDice);$('keepRoll').addEventListener('click',keepRoll);$('bank').addEventListener('click',bank);$('newGame').addEventListener('click',setup);$('mode').addEventListener('change',setup);$('target').addEventListener('change',setup);$('difficulty').addEventListener('change',save);if(!restore())setup();else{render();if(isBotTurn())setTimeout(botPlay,350);}})();
