(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HexlineEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
const DIR=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];function idx(s,r,c){return r*s.size+c}function rc(s,i){return[Math.floor(i/s.size),i%s.size]}function inside(s,r,c){return r>=0&&c>=0&&r<s.size&&c<s.size}function neighbors(s,i){const[r,c]=rc(s,i);return DIR.map(([dr,dc])=>[r+dr,c+dc]).filter(([a,b])=>inside(s,a,b)).map(([a,b])=>idx(s,a,b))}
function createGame(o){o=o||{};const size=Math.max(3,Math.min(15,Number(o.size)||11));return{size,board:Array(size*size).fill(-1),current:0,colorOfPlayer:[0,1],moves:[],swapEnabled:o.swap!==false,swapUsed:false,over:false,winner:null};}function clone(s){return{...s,board:s.board.slice(),colorOfPlayer:s.colorOfPlayer.slice(),moves:s.moves.map(x=>({...x}))}}
function connected(s,color){const n=s.size,seen=new Set(),q=[];if(color===0){for(let r=0;r<n;r++){const i=idx(s,r,0);if(s.board[i]===color){seen.add(i);q.push(i)}}}else{for(let c=0;c<n;c++){const i=idx(s,0,c);if(s.board[i]===color){seen.add(i);q.push(i)}}}while(q.length){const i=q.shift(),[r,c]=rc(s,i);if((color===0&&c===n-1)||(color===1&&r===n-1))return true;for(const j of neighbors(s,i))if(s.board[j]===color&&!seen.has(j)){seen.add(j);q.push(j)}}return false}
function winner(s){for(const color of[0,1])if(connected(s,color))return s.colorOfPlayer.indexOf(color);return null}
function legalActions(s){if(s.over)return[];const out=s.board.map((v,i)=>v===-1?{type:'place',at:i}:null).filter(Boolean);if(s.swapEnabled&&!s.swapUsed&&s.moves.length===1&&s.current===1)out.unshift({type:'swap'});return out}
function apply(input,a){const s=clone(input);if(s.over)throw new Error('Game over');const legal=legalActions(s).some(x=>x.type===a.type&&x.at===a.at);if(!legal)throw new Error('Illegal action');if(a.type==='swap'){s.colorOfPlayer=[1,0];s.swapUsed=true;s.moves.push({type:'swap',player:1});s.current=0;return s}const p=s.current;s.board[a.at]=s.colorOfPlayer[p];s.moves.push({type:'place',at:a.at,player:p,color:s.colorOfPlayer[p]});const w=winner(s);if(w!==null){s.over=true;s.winner=w}else s.current=1-p;return s}
function dijkstraCost(s,color){const n=s.size,N=n*n,dist=Array(N).fill(Infinity),used=Array(N).fill(false),starts=[];if(color===0)for(let r=0;r<n;r++)starts.push(idx(s,r,0));else for(let c=0;c<n;c++)starts.push(idx(s,0,c));const cost=i=>s.board[i]===color?0:s.board[i]===-1?1:99;for(const i of starts)dist[i]=cost(i);for(let k=0;k<N;k++){let u=-1,b=Infinity;for(let i=0;i<N;i++)if(!used[i]&&dist[i]<b){b=dist[i];u=i}if(u<0)break;used[u]=true;for(const v of neighbors(s,u)){const nd=dist[u]+cost(v);if(nd<dist[v])dist[v]=nd}}let ans=Infinity;if(color===0)for(let r=0;r<n;r++)ans=Math.min(ans,dist[idx(s,r,n-1)]);else for(let c=0;c<n;c++)ans=Math.min(ans,dist[idx(s,n-1,c)]);return ans}
function evaluate(s,root){if(s.over)return s.winner===root?1e6:-1e6;const my=s.colorOfPlayer[root],op=s.colorOfPlayer[1-root];return(dijkstraCost(s,op)-dijkstraCost(s,my))*100}
function immediate(s,p){for(const a of legalActions(s).filter(x=>x.type==='place')){const n=apply({...s,current:p},a);if(n.over&&n.winner===p)return a}return null}
function seeded(seed){let x=(seed>>>0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function randomPlayout(s,root,rng){let n=clone(s),limit=n.board.length-n.moves.filter(m=>m.type==='place').length;while(!n.over&&limit-->0){const a=legalActions(n).filter(x=>x.type==='place');if(!a.length)break;n=apply(n,a[Math.floor(rng()*a.length)])}return n.winner===root?1:n.winner===null?0:-1}
function botAction(s,difficulty,rng){const acts=legalActions(s);if(!acts.length)return null;rng=rng||Math.random;if(difficulty==='easy')return acts[Math.floor(rng()*acts.length)];if(acts.some(a=>a.type==='swap')&&s.size>=7){const first=s.moves[0].at,[r,c]=rc(s,first),center=(s.size-1)/2;if(Math.abs(r-center)+Math.abs(c-center)<s.size/3)return{type:'swap'}}const win=immediate(s,s.current);if(win)return win;const opp=1-s.current,block=immediate({...s,current:opp},opp);if(block&&s.board[block.at]===-1)return{type:'place',at:block.at};const root=s.current,places=acts.filter(a=>a.type==='place');let scored=places.map(a=>{const n=apply(s,a);return{a,v:evaluate(n,root)}}).sort((x,y)=>y.v-x.v);if(difficulty==='medium'||s.size>9)return scored[0].a;const top=scored.slice(0,Math.min(10,scored.length));let best=top[0].a,bv=-Infinity;for(const item of top){const n=apply(s,item.a),rr=seeded((item.a+1)*2654435761+s.moves.length);let total=0;for(let k=0;k<24;k++)total+=randomPlayout(n,root,rr);const v=item.v+total*12;if(v>bv){bv=v;best=item.a}}return best}
return{DIR,createGame,clone,idx,rc,neighbors,connected,winner,legalActions,apply,dijkstraCost,evaluate,botAction};});
