(function(){
'use strict';
const E=window.PatternFoundryEngine, STORAGE='osbg-pattern-foundry-v1';
const $=id=>document.getElementById(id);
const els={mode:$('mode'),players:$('players'),difficulty:$('difficulty'),newGame:$('newGame'),round:$('round'),turn:$('turn'),selection:$('selection'),factories:$('factories'),center:$('center'),playersArea:$('playersArea'),status:$('status')};
let state=null,selection=null,botTimer=null;

function playerName(i){return els.mode.value==='bot'&&i===1?'Computer':`Player ${i+1}`;}
function colorClass(c){return E.COLORS[c];}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({state,mode:els.mode.value,players:els.players.value,difficulty:els.difficulty.value}));}catch(_){}}
function load(){try{const data=JSON.parse(localStorage.getItem(STORAGE)||'null');if(!data||!data.state||!Array.isArray(data.state.players))return false;state=data.state;els.mode.value=data.mode||'bot';els.players.value=String(data.players||state.numPlayers||2);els.difficulty.value=data.difficulty||'medium';return true;}catch(_){return false;}}
function modeRules(){const bot=els.mode.value==='bot';if(bot){els.players.value='2';els.players.disabled=true;}else els.players.disabled=false;els.difficulty.disabled=!bot;}
function newGame(){clearTimeout(botTimer);selection=null;modeRules();const count=els.mode.value==='bot'?2:Number(els.players.value);state=E.createGame({players:count,seed:`${Date.now()}-${Math.random()}`});save();render();maybeBot();}
function sourceDisabled(){return state.over||(els.mode.value==='bot'&&state.current===1);}
function sameSelection(source,index,color){return selection&&selection.source===source&&selection.index===index&&selection.color===color;}
function tileButton(source,index,color,count){const b=document.createElement('button');b.type='button';b.className=`tile-button ${colorClass(color)}${sameSelection(source,index,color)?' selected':''}`;b.setAttribute('aria-label',`${count} ${E.COLORS[color]} tile${count===1?'':'s'} from ${source==='center'?'center':`workshop ${index+1}`}`);b.disabled=sourceDisabled();const n=document.createElement('span');n.className='count';n.textContent=count;b.appendChild(n);b.addEventListener('click',()=>selectSource(source,index,color));return b;}
function selectSource(source,index,color){if(sourceDisabled())return;selection={source,index,color};els.status.textContent=`Selected ${E.COLORS[color]}. Choose a highlighted pattern line or the floor.`;render();}
function moveFor(line){return selection?{source:selection.source,index:selection.index,color:selection.color,line}:null;}
function destinationLegal(line){if(!selection||state.over)return false;return !E.validateMove(state,moveFor(line));}
function applyDestination(line){if(!destinationLegal(line))return;const move=moveFor(line);try{state=E.draft(state,move);selection=null;save();render();maybeBot();}catch(err){els.status.textContent=err.message;}}
function renderFactories(){els.factories.innerHTML='';state.factories.forEach((factory,index)=>{const el=document.createElement('div');el.className='factory';const label=document.createElement('span');label.className='factory-number';label.textContent=`W${index+1}`;el.appendChild(label);let any=false;factory.forEach((count,color)=>{if(count){any=true;el.appendChild(tileButton('factory',index,color,count));}});if(!any){const empty=document.createElement('span');empty.className='empty-note';empty.textContent='Empty';el.appendChild(empty);}els.factories.appendChild(el);});}
function renderCenter(){els.center.innerHTML='';let any=false;if(state.firstToken){const marker=document.createElement('div');marker.className='lead-marker';marker.textContent='★';marker.title='Lead marker: first center drafter starts next round and takes one floor space';els.center.appendChild(marker);any=true;}state.center.forEach((count,color)=>{if(count){any=true;els.center.appendChild(tileButton('center',null,color,count));}});if(!any){const empty=document.createElement('span');empty.className='empty-note';empty.textContent='Center is empty';els.center.appendChild(empty);}}
function makePatternRow(player,row,active){const line=player.lines[row],el=document.createElement('div');el.className=`pattern-row${active&&destinationLegal(row)?' legal':''}`;el.setAttribute('aria-label',`Pattern line ${row+1}, ${line.count} of ${row+1} filled`);for(let i=0;i<row+1;i++){const slot=document.createElement('div');slot.className='slot';if(i>=row+1-line.count){slot.classList.add('filled',colorClass(line.color));}el.appendChild(slot);}if(active&&destinationLegal(row)){el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('click',()=>applyDestination(row));el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();applyDestination(row);}});}return el;}
function makeWall(player){const wall=document.createElement('div');wall.className='wall';for(let r=0;r<5;r++)for(let c=0;c<5;c++){const cell=document.createElement('div');const placed=player.wall[r][c],ghost=placed==null?E.WALL_PATTERN[r][c]:placed;cell.className=`wall-cell ${colorClass(ghost)}${placed!=null?' filled':''}`;cell.setAttribute('aria-label',placed==null?`Empty wall position for ${E.COLORS[ghost]}`:`${E.COLORS[placed]} tile`);wall.appendChild(cell);}return wall;}
function makeFloor(player,active){const wrap=document.createElement('div');wrap.className='floor-wrap';const label=document.createElement('div');label.className='floor-label';label.innerHTML='<span>Floor</span><span>−1 · −1 · −2 · −2 · −2 · −3 · −3</span>';wrap.appendChild(label);const floor=document.createElement('div');floor.className='floor';for(let i=0;i<7;i++){const cell=document.createElement('div'),item=player.floor[i];cell.className='floor-slot';cell.textContent=String(E.FLOOR_PENALTIES[i]);if(item!=null){if(item==='marker'){cell.classList.add('marker');cell.textContent='★';}else{cell.classList.add('filled',colorClass(item));cell.textContent='';}}if(active&&destinationLegal(5))cell.classList.add('legal');floor.appendChild(cell);}if(active&&destinationLegal(5)){floor.tabIndex=0;floor.setAttribute('role','button');floor.setAttribute('aria-label','Send selected tiles to the floor');floor.addEventListener('click',()=>applyDestination(5));floor.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();applyDestination(5);}});}wrap.appendChild(floor);if(player.floor.length>7){const overflow=document.createElement('div');overflow.className='overflow';overflow.textContent=`${player.floor.length-7} additional tile${player.floor.length-7===1?'':'s'} will be discarded without extra penalty.`;wrap.appendChild(overflow);}return wrap;}
function renderPlayers(){els.playersArea.innerHTML='';state.players.forEach((player,i)=>{const board=document.createElement('article'),active=!state.over&&state.current===i&&!(els.mode.value==='bot'&&i===1);board.className=`player-board${state.current===i&&!state.over?' active':''}`;const head=document.createElement('div');head.className='player-head';const h=document.createElement('h2');h.textContent=playerName(i);if(state.over&&state.winners.includes(i))h.classList.add('winner');const score=document.createElement('span');score.className='score-badge';score.textContent=`${player.score} pts`;head.append(h,score);board.appendChild(head);const grid=document.createElement('div');grid.className='board-grid';const lines=document.createElement('div');lines.className='pattern-lines';for(let r=0;r<5;r++)lines.appendChild(makePatternRow(player,r,active));grid.append(lines,makeWall(player));board.appendChild(grid);board.appendChild(makeFloor(player,active));els.playersArea.appendChild(board);});}
function currentStatus(){if(state.over){const winners=state.winners.map(playerName);return winners.length===1?`${winners[0]} wins with ${state.players[state.winners[0]].score} points.`:`Tie: ${winners.join(' and ')}.`;}if(els.mode.value==='bot'&&state.current===1)return`${playerName(1)} is choosing tiles…`;if(selection)return`Selected ${E.COLORS[selection.color]}. Choose a highlighted destination.`;return`${playerName(state.current)}: choose a color from a workshop or the center.`;}
function render(){modeRules();els.round.textContent=state.round;els.turn.textContent=state.over?'Game over':playerName(state.current);els.selection.textContent=selection?E.COLORS[selection.color]:'Choose tiles';els.status.textContent=currentStatus();renderFactories();renderCenter();renderPlayers();}
function maybeBot(){clearTimeout(botTimer);if(!state||state.over||els.mode.value!=='bot'||state.current!==1)return;botTimer=setTimeout(()=>{const move=E.botMove(state,els.difficulty.value);if(!move)return;state=E.draft(state,move);save();render();maybeBot();},els.difficulty.value==='hard'?420:300);}

els.newGame.addEventListener('click',newGame);
els.mode.addEventListener('change',newGame);
els.players.addEventListener('change',newGame);
els.difficulty.addEventListener('change',()=>{save();maybeBot();});
if(!load())newGame();else{modeRules();render();maybeBot();}
})();
