(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HighTableEngine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function seeded(seed){let x=(Number(seed)>>>0)||0x9e3779b9;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}
function rank(c){return c%13+2}function suit(c){return Math.floor(c/13)}function makeDeck(){return Array.from({length:52},(_,i)=>i)}function shuffle(deck,seed){const a=deck.slice(),r=seeded(seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cardStrength(r,revolution){const normal=r===2?15:r;return revolution?-normal:normal}
function createGame(o){o=o||{};const players=Math.max(3,Math.min(8,Number(o.players)||4)),deck=shuffle(makeDeck(),o.seed==null?Date.now():o.seed),hands=Array.from({length:players},()=>[]);deck.forEach((c,i)=>hands[i%players].push(c));hands.forEach(h=>h.sort((a,b)=>cardStrength(rank(a),false)-cardStrength(rank(b),false)||suit(a)-suit(b)));return{players,hands,current:0,table:null,lastPlayPlayer:null,passes:Array(players).fill(false),finished:[],over:false,revolution:false,options:{revolution:o.revolution!==false,clearRank:o.clearRank==null?null:Number(o.clearRank)},history:[]}}
function clone(s){return{...s,hands:s.hands.map(h=>h.slice()),table:s.table?{...s.table,cards:s.table.cards.slice()}:null,passes:s.passes.slice(),finished:s.finished.slice(),options:{...s.options},history:s.history.map(x=>({...x,cards:x.cards?x.cards.slice():undefined}))}}
function isActive(s,p){return !s.finished.includes(p)&&s.hands[p].length>0}function activePlayers(s){return Array.from({length:s.players},(_,i)=>i).filter(p=>isActive(s,p))}
function nextActive(s,p){for(let k=1;k<=s.players;k++){const q=(p+k)%s.players;if(isActive(s,q))return q}return null}
function sameRank(cards){return cards.length>0&&cards.every(c=>rank(c)===rank(cards[0]))}
function canPlay(s,p,cards){if(s.over||p!==s.current||!isActive(s,p)||!sameRank(cards))return false;const hand=s.hands[p],copy=hand.slice();for(const c of cards){const i=copy.indexOf(c);if(i<0)return false;copy.splice(i,1)}if(!s.table)return true;if(cards.length!==s.table.count)return false;return cardStrength(rank(cards[0]),s.revolution)>cardStrength(s.table.rank,s.revolution)}
function legalGroups(s,p){p=p==null?s.current:p;if(s.over||p!==s.current||!isActive(s,p))return[];const by=new Map();for(const c of s.hands[p]){const r=rank(c);if(!by.has(r))by.set(r,[]);by.get(r).push(c)}const out=[];for(const [r,cards] of by){const needed=s.table?s.table.count:null;const sizes=needed?[needed]:Array.from({length:cards.length},(_,i)=>i+1);for(const n of sizes){if(n>cards.length)continue;const combo=cards.slice(0,n);if(canPlay(s,p,combo))out.push(combo)}}return out}
function resetTrick(s,start){s.table=null;s.lastPlayPlayer=null;s.passes.fill(false);s.current=start==null?(activePlayers(s)[0]??0):start;s.history.push({type:'reset',player:s.current})}
function finishIfNeeded(s,p){if(s.hands[p].length===0&&!s.finished.includes(p)){s.finished.push(p);s.passes[p]=true;if(s.finished.length===s.players-1){const last=Array.from({length:s.players},(_,i)=>i).find(i=>!s.finished.includes(i));if(last!=null)s.finished.push(last);s.over=true}}}
function maybeResetAfterPass(s){if(!s.table)return false;const act=activePlayers(s);const others=act.filter(p=>p!==s.lastPlayPlayer);if(others.length===0||others.every(p=>s.passes[p])){const start=isActive(s,s.lastPlayPlayer)?s.lastPlayPlayer:nextActive(s,s.lastPlayPlayer==null?s.current:s.lastPlayPlayer);resetTrick(s,start);return true}return false}
function play(input,cards){const s=clone(input),p=s.current;if(!canPlay(s,p,cards))throw new Error('Illegal play');for(const c of cards){const i=s.hands[p].indexOf(c);s.hands[p].splice(i,1)}const r=rank(cards[0]);s.table={rank:r,count:cards.length,cards:cards.slice()};s.lastPlayPlayer=p;s.passes.fill(false);s.history.push({type:'play',player:p,cards:cards.slice(),rank:r,count:cards.length});if(s.options.revolution&&cards.length===4){s.revolution=!s.revolution;s.history.push({type:'revolution',player:p})}const clear=s.options.clearRank!=null&&r===s.options.clearRank;finishIfNeeded(s,p);if(s.over)return s;if(clear){const start=nextActive(s,p);resetTrick(s,start);return s}const n=nextActive(s,p);if(n==null){s.over=true;return s}s.current=n;return s}
function pass(input){const s=clone(input),p=s.current;if(s.over||!s.table||!isActive(s,p)||p===s.lastPlayPlayer)throw new Error('Cannot pass');s.passes[p]=true;s.history.push({type:'pass',player:p});const n=nextActive(s,p);s.current=n==null?p:n;if(!maybeResetAfterPass(s)&&s.passes[s.current]){let guard=0;while(s.passes[s.current]&&guard++<s.players){s.current=nextActive(s,s.current)??s.current}}return s}
function groupValue(s,g){const r=rank(g[0]),high=cardStrength(r,s.revolution);let score=-high*2-g.length*3;const same=s.hands[s.current].filter(c=>rank(c)===r).length;if(same===g.length)score+=4;if(r===2)score-=12;if(g.length>=3)score-=5;return score}
function botAction(s,difficulty,rng){rng=rng||Math.random;const groups=legalGroups(s);if(!groups.length)return s.table?{type:'pass'}:null;if(difficulty==='easy')return{type:'play',cards:groups[Math.floor(rng()*groups.length)]};let scored=groups.map(g=>({g,v:groupValue(s,g)}));if(difficulty==='hard'){scored=scored.map(x=>{const left=s.hands[s.current].length-x.g.length;const control=rank(x.g[0])===2?15:rank(x.g[0]);return{...x,v:x.v-left*.35+(left===0?100:0)+(s.table&&control<8?3:0)}})}scored.sort((a,b)=>b.v-a.v);return{type:'play',cards:scored[0].g}}
function playerView(s,p){return{players:s.players,current:s.current,hand:s.hands[p].slice(),handCounts:s.hands.map(h=>h.length),table:s.table?{...s.table,cards:s.table.cards.slice()}:null,finished:s.finished.slice(),revolution:s.revolution,over:s.over};}
return{seeded,rank,suit,makeDeck,shuffle,cardStrength,createGame,clone,isActive,activePlayers,nextActive,sameRank,canPlay,legalGroups,play,pass,botAction,playerView};});
