(()=>{'use strict';
const EMPTY=0,BLACK=1,WHITE=-1,DIRS=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],WEIGHTS=[[180,-45,25,8,8,25,-45,180],[-45,-80,-8,-8,-8,-8,-80,-45],[25,-8,18,4,4,18,-8,25],[8,-8,4,3,3,4,-8,8],[8,-8,4,3,3,4,-8,8],[25,-8,18,4,4,18,-8,25],[-45,-80,-8,-8,-8,-8,-80,-45],[180,-45,25,8,8,25,-45,180]];
const boardEl=document.getElementById('board'),statusEl=document.getElementById('status'),blackScoreEl=document.getElementById('black-score'),whiteScoreEl=document.getElementById('white-score'),blackCard=document.getElementById('black-card'),whiteCard=document.getElementById('white-card'),blackLabel=document.getElementById('black-label'),whiteLabel=document.getElementById('white-label'),turnPill=document.getElementById('turn-pill'),difficultyEl=document.getElementById('difficulty'),newGameBtn=document.getElementById('new-game'),showHintsEl=document.getElementById('show-hints'),colorButtons=[...document.querySelectorAll('[data-color]')],cells=[];
let board=createInitialBoard(),human=BLACK,computer=WHITE,current=BLACK,gameOver=false,computerThinking=false,lastMove=null,gameToken=0,showHints=readHintsPreference();
function createInitialBoard(){const b=Array.from({length:8},()=>Array(8).fill(EMPTY));b[3][3]=WHITE;b[3][4]=BLACK;b[4][3]=BLACK;b[4][4]=WHITE;return b}
function readHintsPreference(){try{const s=localStorage.getItem('discshift-show-hints');return s===null?true:s==='true'}catch{return true}}
function saveHintsPreference(){try{localStorage.setItem('discshift-show-hints',String(showHints))}catch{}}
const inBounds=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
function flipsForMove(b,r,c,p){if(!inBounds(r,c)||b[r][c]!==EMPTY)return[];const flips=[];for(const[dr,dc]of DIRS){const line=[];let rr=r+dr,cc=c+dc;while(inBounds(rr,cc)&&b[rr][cc]===-p){line.push([rr,cc]);rr+=dr;cc+=dc}if(line.length&&inBounds(rr,cc)&&b[rr][cc]===p)flips.push(...line)}return flips}
function legalMoves(b,p){const out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const f=flipsForMove(b,r,c,p);if(f.length)out.push({r,c,flips:f})}return out}
function applyMove(b,m,p){const n=b.map(row=>row.slice());n[m.r][m.c]=p;for(const[r,c]of m.flips)n[r][c]=p;return n}
function counts(b){let black=0,white=0;for(const row of b)for(const v of row){if(v===BLACK)black++;else if(v===WHITE)white++}return{black,white}}
function frontierCount(b,p){let n=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]===p&&DIRS.some(([dr,dc])=>inBounds(r+dr,c+dc)&&b[r+dr][c+dc]===EMPTY))n++;return n}
function stableEdgeApprox(b,p){let n=0;const specs=[[0,0,0,1],[0,0,1,0],[0,7,0,-1],[0,7,1,0],[7,0,0,1],[7,0,-1,0],[7,7,0,-1],[7,7,-1,0]];for(const[cr,cc,dr,dc]of specs){if(b[cr][cc]!==p)continue;let r=cr,c=cc;while(inBounds(r,c)&&b[r][c]===p){n++;r+=dr;c+=dc}}return n}
function evaluate(b,p){let position=0,mine=0,theirs=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++){if(b[r][c]===p){position+=WEIGHTS[r][c];mine++}else if(b[r][c]===-p){position-=WEIGHTS[r][c];theirs++}}const myMoves=legalMoves(b,p).length,theirMoves=legalMoves(b,-p).length,mobility=14*(myMoves-theirMoves),frontier=5*(frontierCount(b,-p)-frontierCount(b,p)),stability=18*(stableEdgeApprox(b,p)-stableEdgeApprox(b,-p)),occupied=mine+theirs,empty=64-occupied,parity=empty<14?(empty%2?5:-5):0,discWeight=occupied>50?5:occupied>42?1.7:.25;return position+mobility+frontier+stability+parity+discWeight*(mine-theirs)}
function orderedMoves(ms){return ms.slice().sort((a,b)=>WEIGHTS[b.r][b.c]-WEIGHTS[a.r][a.c])}
function minimax(b,turn,max,depth,alpha,beta){const ms=legalMoves(b,turn),other=legalMoves(b,-turn);if(depth<=0||(!ms.length&&!other.length))return evaluate(b,max);if(!ms.length)return minimax(b,-turn,max,depth-1,alpha,beta);if(turn===max){let v=-Infinity;for(const m of orderedMoves(ms)){v=Math.max(v,minimax(applyMove(b,m,turn),-turn,max,depth-1,alpha,beta));alpha=Math.max(alpha,v);if(alpha>=beta)break}return v}let v=Infinity;for(const m of orderedMoves(ms)){v=Math.min(v,minimax(applyMove(b,m,turn),-turn,max,depth-1,alpha,beta));beta=Math.min(beta,v);if(alpha>=beta)break}return v}
function chooseComputerMove(b,p,difficulty){const ms=legalMoves(b,p);if(difficulty==='easy')return ms[Math.floor(Math.random()*ms.length)];const c=counts(b),occupied=c.black+c.white,depth=difficulty==='hard'?(occupied>48?7:occupied>36?6:5):3;let best=ms[0],bestScore=-Infinity;for(const m of orderedMoves(ms)){const v=minimax(applyMove(b,m,p),-p,p,depth-1,-Infinity,Infinity);if(v>bestScore){bestScore=v;best=m}}return best}
function initializeBoardDom(){const f=document.createDocumentFragment();for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.type='button';cell.className='cell';cell.setAttribute('role','gridcell');cell.addEventListener('click',()=>{if(gameOver||computerThinking||current!==human)return;const flips=flipsForMove(board,r,c,human);if(flips.length)humanMove({r,c,flips})});cells.push(cell);f.append(cell)}boardEl.append(f)}
function syncCell(cell,r,c,legalSet){const legal=legalSet.has(`${r},${c}`);cell.classList.toggle('legal',legal);cell.classList.toggle('show-hint',legal&&showHints);cell.classList.toggle('last-move',Boolean(lastMove&&lastMove.r===r&&lastMove.c===c));cell.setAttribute('aria-label',legal?`Legal move at row ${r+1}, column ${c+1}`:`Row ${r+1}, column ${c+1}`);const v=board[r][c];let piece=cell.firstElementChild;if(v===EMPTY){piece?.remove();return}if(!piece){piece=document.createElement('span');piece.className='piece';cell.append(piece)}piece.classList.toggle('black',v===BLACK);piece.classList.toggle('white',v===WHITE)}
function render(){const legal=!gameOver&&current===human&&!computerThinking?legalMoves(board,human):[],set=new Set(legal.map(m=>`${m.r},${m.c}`));for(let r=0;r<8;r++)for(let c=0;c<8;c++)syncCell(cells[r*8+c],r,c,set);const{black,white}=counts(board);blackScoreEl.textContent=black;whiteScoreEl.textContent=white;blackCard.classList.toggle('active',current===BLACK&&!gameOver);whiteCard.classList.toggle('active',current===WHITE&&!gameOver);blackLabel.textContent=human===BLACK?'You':'Computer';whiteLabel.textContent=human===WHITE?'You':'Computer';turnPill.textContent=gameOver?'Game over':computerThinking?'Computer thinking…':current===human?'Your turn':'Computer turn'}
const setStatus=t=>statusEl.textContent=t;
function humanMove(m){if(gameOver||computerThinking||current!==human)return;board=applyMove(board,m,human);lastMove={r:m.r,c:m.c};current=computer;render();resolveTurnFlow()}
function resolveTurnFlow(){if(gameOver)return;const here=legalMoves(board,current),other=legalMoves(board,-current);if(!here.length&&!other.length){finishGame();return}if(!here.length){const skipped=current;current=-current;setStatus(`${skipped===human?'You have':'The computer has'} no legal move, so the turn passes.`);render();if(current===computer)queueComputerMove();return}if(current===computer){setStatus('Computer is choosing a move…');queueComputerMove()}else{setStatus(showHints?'Your turn. Choose a highlighted square.':'Your turn. Choose a legal square.');render()}}
function queueComputerMove(){const token=gameToken;computerThinking=true;render();setTimeout(()=>{if(token!==gameToken||gameOver||current!==computer)return;const ms=legalMoves(board,computer);if(!ms.length){computerThinking=false;resolveTurnFlow();return}const m=chooseComputerMove(board,computer,difficultyEl.value);board=applyMove(board,m,computer);lastMove={r:m.r,c:m.c};computerThinking=false;current=human;render();resolveTurnFlow()},220)}
function finishGame(){gameOver=true;computerThinking=false;const{black,white}=counts(board),hs=human===BLACK?black:white,cs=human===BLACK?white:black;if(hs>cs)setStatus(`You win ${hs}–${cs}. Nice game.`);else if(hs<cs)setStatus(`Computer wins ${cs}–${hs}. Try another round.`);else setStatus(`Draw: ${hs}–${cs}.`);render()}
function startGame(){gameToken++;board=createInitialBoard();current=BLACK;gameOver=false;computerThinking=false;lastMove=null;setStatus(human===BLACK?(showHints?'You are Black. Place a disc on a highlighted square.':'You are Black. Place a disc on a legal square.'):'You are White. The computer moves first.');render();if(computer===BLACK)queueComputerMove()}
colorButtons.forEach(btn=>btn.addEventListener('click',()=>{human=btn.dataset.color==='black'?BLACK:WHITE;computer=-human;colorButtons.forEach(b=>b.classList.toggle('active',b===btn));startGame()}));showHintsEl.checked=showHints;showHintsEl.addEventListener('change',()=>{showHints=showHintsEl.checked;saveHintsPreference();render();if(!gameOver&&current===human&&!computerThinking)setStatus(showHints?'Your turn. Choose a highlighted square.':'Your turn. Move hints are hidden.')});newGameBtn.addEventListener('click',startGame);initializeBoardDom();startGame();})();
