import {createInitialState,generateLegalMoves,applyMove,status,RED_SIDE,BLACK_SIDE,sideOf,isKing,serializeState,deserializeState,validateState} from './engine.js';
import {loadLocalGame,saveLocalGame,loadSettings,saveSettings} from './persistence.js';
const $=s=>document.querySelector(s),boardEl=$('#board'),modeEl=$('#mode'),difficultyEl=$('#difficulty'),thinkEl=$('#thinkTime');
let state=createInitialState(),selected=null,aiWorker=null,locked=false,peer=null,conn=null,onlineRole=null;
const pieceNames={1:'red',2:'black',3:'red',4:'black'},coord=i=>`${String.fromCharCode(97+(i%8))}${8-Math.floor(i/8)}`,PEERJS_URL='https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js';
const currentMoves=()=>generateLegalMoves(state),movesFrom=i=>currentMoves().filter(m=>m.from===i),cap=s=>s[0].toUpperCase()+s.slice(1);
function isHumanTurn(){if(modeEl.value==='local')return true;if(modeEl.value==='ai')return state.turn===RED_SIDE;if(modeEl.value==='online')return !!conn?.open&&state.turn===onlineRole;return true;}
function render(){const legal=currentMoves(),st=status(state),forced=legal.length&&legal[0].isCapture;boardEl.innerHTML='';for(let i=0;i<64;i++){const r=Math.floor(i/8),c=i%8,sq=document.createElement('button');sq.className=`square ${(r+c)%2?'dark':'light'}`;sq.dataset.i=i;sq.setAttribute('aria-label',coord(i));if(i===selected)sq.classList.add('selected');if(selected!==null&&movesFrom(selected).some(m=>m.to===i))sq.classList.add('legal');if(forced&&legal.some(m=>m.from===i))sq.classList.add('forced');const p=state.board[i];if(p){const el=document.createElement('div');el.className=`piece ${pieceNames[p]} ${isKing(p)?'king':''}`;sq.append(el);}sq.onclick=()=>clickSquare(i);boardEl.append(sq);}$('#turnDot').className=`turn-dot ${state.turn}`;$('#statusText').textContent=st.over?`${cap(st.winner)} wins`:`${cap(state.turn)} to move`;$('#hint').textContent=forced?'Capture required — highlighted pieces must jump.':selected!==null?'Choose a highlighted destination.':'Tap a piece to see legal moves.';const redLeft=state.board.filter(p=>sideOf(p)===RED_SIDE).length,blackLeft=state.board.filter(p=>sideOf(p)===BLACK_SIDE).length;$('#score').textContent=`${redLeft} – ${blackLeft}`;$('#capturedRed').innerHTML=Array(12-redLeft).fill('<i class="mini red"></i>').join('');$('#capturedBlack').innerHTML=Array(12-blackLeft).fill('<i class="mini black"></i>').join('');$('#history').innerHTML=(state.history||[]).map(m=>`<li>${coord(m.from)}${m.isCapture?'×':'–'}${m.path.slice(1).map(coord).join('×')}</li>`).join('');if(st.over&&!$('#gameOverDialog').open){$('#gameOverTitle').textContent=`${cap(st.winner)} wins`;$('#gameOverReason').textContent=st.reason==='no-legal-moves'?'The opponent has no legal moves.':'All opposing pieces were captured.';$('#gameOverDialog').showModal();}if(modeEl.value==='ai'||modeEl.value==='local')saveLocalGame({mode:modeEl.value,state});maybeAI();}
function clickSquare(i){if(locked||status(state).over||!isHumanTurn())return;const p=state.board[i],legal=currentMoves();if(sideOf(p)===state.turn&&legal.some(m=>m.from===i)){selected=i;render();return;}if(selected===null)return;const options=movesFrom(selected).filter(m=>m.to===i);if(options.length)playMove(options[0],true);}
async function animateMove(move){const source=boardEl.querySelector(`[data-i="${move.from}"] .piece`);if(!source?.animate)return;const start=source.getBoundingClientRect(),target=boardEl.querySelector(`[data-i="${move.to}"]`);if(!target)return;const r=target.getBoundingClientRect(),dx=r.left-start.left,dy=r.top-start.top;await source.animate([{transform:'translate(0,0)'},{transform:`translate(${dx/2}px,${dy/2-18}px) scale(1.08)`,offset:.5},{transform:`translate(${dx}px,${dy}px)`}],{duration:180,easing:'ease-in-out'}).finished.catch(()=>{});}
async function playMove(move,broadcast=false){locked=true;await animateMove(move);state=applyMove(state,move);selected=null;locked=false;if(broadcast&&modeEl.value==='online'&&conn?.open)conn.send({type:'move',move});render();}
function maybeAI(){if(modeEl.value!=='ai'||state.turn!==BLACK_SIDE||status(state).over||locked)return;locked=true;$('#thinking').classList.remove('hidden');aiWorker?.terminate();aiWorker=new Worker('./ai-worker.js',{type:'module'});aiWorker.onmessage=e=>{locked=false;$('#thinking').classList.add('hidden');if(e.data.move)playMove(e.data.move,false);};aiWorker.onerror=()=>{locked=false;$('#thinking').classList.add('hidden');$('#hint').textContent='The AI worker could not start. Reload and try again.';};aiWorker.postMessage({state,level:difficultyEl.value,timeMs:Number(thinkEl.value)});}
function reset(){state=createInitialState($('#firstPlayer').value);selected=null;locked=false;if($('#gameOverDialog').open)$('#gameOverDialog').close();render();if(modeEl.value==='online'&&conn?.open&&onlineRole===RED_SIDE)conn.send({type:'state',state});}
function savePreferences(){saveSettings({mode:modeEl.value,difficulty:difficultyEl.value,thinkTime:thinkEl.value,firstPlayer:$('#firstPlayer').value});}
function syncModeUI(){const ai=modeEl.value==='ai',online=modeEl.value==='online';$('#difficultyWrap').classList.toggle('hidden',!ai);$('#thinkWrap').classList.toggle('hidden',!ai);$('#onlinePanel').classList.toggle('hidden',!online);}
function restore(){const s=loadSettings();if(['ai','local','online'].includes(s.mode))modeEl.value=s.mode;if(['easy','medium','hard'].includes(s.difficulty))difficultyEl.value=s.difficulty;if(['250','700','1500','3000'].includes(String(s.thinkTime)))thinkEl.value=String(s.thinkTime);if(['red','black'].includes(s.firstPlayer))$('#firstPlayer').value=s.firstPlayer;const saved=loadLocalGame();if(saved&&(saved.mode==='ai'||saved.mode==='local')&&saved.mode===modeEl.value){try{state=validateState(saved.state)}catch{state=createInitialState($('#firstPlayer').value)}}}
const roomId=code=>`crown-jump-${code.toLowerCase()}`,randomCode=()=>Math.random().toString(36).slice(2,7).toUpperCase(),setOnlineStatus=t=>$('#onlineStatus').textContent=t;
function ensurePeerJS(){if(globalThis.Peer)return Promise.resolve(globalThis.Peer);return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=PEERJS_URL;s.onload=()=>globalThis.Peer?resolve(globalThis.Peer):reject(new Error('PeerJS unavailable'));s.onerror=reject;document.head.append(s);});}
function cleanupPeer(){try{conn?.close();peer?.destroy()}catch{}conn=null;peer=null;onlineRole=null;}
function wireConnection(c,role){conn=c;onlineRole=role;conn.on('open',()=>{setOnlineStatus(`Connected — you are ${cap(role)}`);if(role===RED_SIDE)conn.send({type:'state',state});render();});conn.on('data',msg=>{if(msg.type==='state'){try{state=validateState(msg.state);selected=null;render()}catch{setOnlineStatus('Invalid state ignored')}}if(msg.type==='move')playMove(msg.move,false).catch(()=>setOnlineStatus('Invalid move ignored'));});conn.on('close',()=>setOnlineStatus('Connection closed'));}
async function host(){cleanupPeer();const code=randomCode();$('#roomCode').value=code;setOnlineStatus('Opening room…');try{const Peer=await ensurePeerJS();peer=new Peer(roomId(code));onlineRole=RED_SIDE;peer.on('open',()=>setOnlineStatus(`Room ${code} ready — share the code`));peer.on('connection',c=>wireConnection(c,RED_SIDE));}catch{setOnlineStatus('Could not load online multiplayer.')}}
async function join(){const code=$('#roomCode').value.trim().toUpperCase();if(!code)return;cleanupPeer();setOnlineStatus('Connecting…');try{const Peer=await ensurePeerJS();peer=new Peer();peer.on('open',()=>wireConnection(peer.connect(roomId(code),{reliable:true}),BLACK_SIDE));}catch{setOnlineStatus('Could not load online multiplayer.')}}
$('#newGame').onclick=reset;$('#playAgain').onclick=reset;$('#closeDialog').onclick=()=>$('#gameOverDialog').close();modeEl.onchange=()=>{cleanupPeer();syncModeUI();savePreferences();reset();};difficultyEl.onchange=savePreferences;thinkEl.onchange=savePreferences;$('#firstPlayer').onchange=()=>{savePreferences();reset();};$('#hostRoom').onclick=host;$('#joinRoom').onclick=join;$('#copyState').onclick=async()=>{const text=serializeState(state);$('#stateBox').value=text;$('#stateBox').classList.remove('hidden');try{await navigator.clipboard.writeText(text)}catch{}};$('#importState').onclick=()=>{const box=$('#stateBox');if(box.classList.contains('hidden')){box.classList.remove('hidden');return;}try{state=deserializeState(box.value);selected=null;render()}catch{alert('That correspondence state is not valid.')}};window.addEventListener('beforeunload',cleanupPeer);restore();syncModeUI();render();
