export const EMPTY=0,RED=1,BLACK=2,RED_KING=3,BLACK_KING=4;
export const RED_SIDE='red',BLACK_SIDE='black';
export const opponent=s=>s===RED_SIDE?BLACK_SIDE:RED_SIDE;
export const sideOf=p=>(p===RED||p===RED_KING)?RED_SIDE:(p===BLACK||p===BLACK_KING)?BLACK_SIDE:null;
export const isKing=p=>p===RED_KING||p===BLACK_KING;
const rc=i=>[Math.floor(i/8),i%8],idx=(r,c)=>r*8+c,inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
const dirs=p=>isKing(p)?[[-1,-1],[-1,1],[1,-1],[1,1]]:sideOf(p)===RED_SIDE?[[-1,-1],[-1,1]]:[[1,-1],[1,1]];
const promotionRow=(s,r)=>s===RED_SIDE?r===0:r===7;
const crowned=p=>p===RED?RED_KING:p===BLACK?BLACK_KING:p;
export const positionKey=s=>`${s.turn}|${s.board.join('')}`;
export function createInitialBoard(){const b=Array(64).fill(EMPTY);for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r*8+c]=BLACK;for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r*8+c]=RED;return b;}
export function createInitialState(first=RED_SIDE){const s={board:createInitialBoard(),turn:first,ply:0,history:[],lastMove:null,positionCounts:{}};s.positionCounts[positionKey(s)]=1;return s;}
function capturesFrom(board,from,piece,path=[from],caps=[]){const [r,c]=rc(from),side=sideOf(piece),out=[];let found=false;for(const [dr,dc] of dirs(piece)){const mr=r+dr,mc=c+dc,lr=r+2*dr,lc=c+2*dc;if(!inside(mr,mc)||!inside(lr,lc))continue;const mid=idx(mr,mc),land=idx(lr,lc);if(board[land]!==EMPTY||sideOf(board[mid])!==opponent(side))continue;found=true;const next=board.slice();next[from]=EMPTY;next[mid]=EMPTY;next[land]=piece;const nextPath=[...path,land],nextCaps=[...caps,mid];if(!isKing(piece)&&promotionRow(side,lr)){out.push({from:path[0],to:land,path:nextPath,captures:nextCaps,promotes:true});continue;}const deeper=capturesFrom(next,land,piece,nextPath,nextCaps);if(deeper.length)out.push(...deeper);else out.push({from:path[0],to:land,path:nextPath,captures:nextCaps,promotes:false});}return found?out:[];}
export function generateLegalMoves(state){const captures=[];for(let i=0;i<64;i++)if(sideOf(state.board[i])===state.turn)captures.push(...capturesFrom(state.board,i,state.board[i]));if(captures.length)return captures.map(m=>({...m,isCapture:true}));const moves=[];for(let i=0;i<64;i++){const p=state.board[i];if(sideOf(p)!==state.turn)continue;const [r,c]=rc(i);for(const [dr,dc] of dirs(p)){const nr=r+dr,nc=c+dc;if(!inside(nr,nc))continue;const to=idx(nr,nc);if(state.board[to]!==EMPTY)continue;moves.push({from:i,to,path:[i,to],captures:[],promotes:!isKing(p)&&promotionRow(state.turn,nr),isCapture:false});}}return moves;}
export function applyMove(state,move){const legal=generateLegalMoves(state),key=JSON.stringify([move.from,move.path,move.captures]);const chosen=legal.find(m=>JSON.stringify([m.from,m.path,m.captures])===key)||legal.find(m=>m.from===move.from&&m.to===move.to&&m.captures.length===(move.captures?.length||0));if(!chosen)throw new Error('Illegal move');const board=state.board.slice();let piece=board[chosen.from];board[chosen.from]=EMPTY;for(const cap of chosen.captures)board[cap]=EMPTY;if(chosen.promotes)piece=crowned(piece);board[chosen.to]=piece;const next={board,turn:opponent(state.turn),ply:(state.ply||0)+1,history:[...(state.history||[]),chosen],lastMove:chosen,positionCounts:{...(state.positionCounts||{})}};const k=positionKey(next);next.positionCounts[k]=(next.positionCounts[k]||0)+1;return next;}
export function status(state){const red=state.board.filter(p=>sideOf(p)===RED_SIDE).length,black=state.board.filter(p=>sideOf(p)===BLACK_SIDE).length;if(!red)return{over:true,winner:BLACK_SIDE,reason:'all-pieces-captured'};if(!black)return{over:true,winner:RED_SIDE,reason:'all-pieces-captured'};if(generateLegalMoves(state).length===0)return{over:true,winner:opponent(state.turn),reason:'no-legal-moves'};return{over:false,winner:null,reason:null};}
export function validateState(x){if(!x||!Array.isArray(x.board)||x.board.length!==64||!x.board.every(p=>Number.isInteger(p)&&p>=0&&p<=4)||![RED_SIDE,BLACK_SIDE].includes(x.turn))throw new Error('Invalid state');const s={board:x.board.slice(),turn:x.turn,ply:Number.isInteger(x.ply)&&x.ply>=0?x.ply:0,history:Array.isArray(x.history)?x.history:[],lastMove:x.lastMove||null,positionCounts:x.positionCounts&&typeof x.positionCounts==='object'?{...x.positionCounts}:{}};if(!Object.keys(s.positionCounts).length)s.positionCounts[positionKey(s)]=1;return s;}
export const serializeState=s=>btoa(unescape(encodeURIComponent(JSON.stringify(validateState(s)))));
export const deserializeState=t=>validateState(JSON.parse(decodeURIComponent(escape(atob(t.trim())))));
