(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CipherloomEngine=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
function normalizeSeed(seed){let x=Number(seed)>>>0;return x||0x6d2b79f5;}function randObj(seed){let x=normalizeSeed(seed);return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/0x100000000;};}
function feedback(secret,guess){if(secret.length!==guess.length)throw new Error('Length mismatch');let exact=0;const sf=new Map(),gf=new Map();for(let i=0;i<secret.length;i++){if(secret[i]===guess[i])exact++;else{sf.set(secret[i],(sf.get(secret[i])||0)+1);gf.set(guess[i],(gf.get(guess[i])||0)+1);}}let partial=0;for(const [k,n] of gf)partial+=Math.min(n,sf.get(k)||0);return{exact,partial};}
function allCodes(length,symbolCount,allowDuplicates){const out=[],cur=[];function rec(){if(cur.length===length){out.push(cur.slice());return;}for(let i=0;i<symbolCount;i++){if(!allowDuplicates&&cur.includes(i))continue;cur.push(i);rec();cur.pop();}}rec();return out;}
function filterCandidates(candidates,guess,result){return candidates.filter(code=>{const f=feedback(code,guess);return f.exact===result.exact&&f.partial===result.partial;});}
function makeSecret(options){options=options||{};const length=Number(options.length)||4,symbolCount=Number(options.symbolCount)||6,allowDuplicates=options.allowDuplicates!==false,rng=randObj(options.seed==null?Date.now():options.seed),secret=[];while(secret.length<length){const v=Math.floor(rng()*symbolCount);if(allowDuplicates||!secret.includes(v))secret.push(v);}return secret;}
function bucketKey(f){return `${f.exact}:${f.partial}`;}
function chooseGuess(candidates,options){options=options||{};if(!candidates.length)return null;if(candidates.length===1)return candidates[0].slice();const length=candidates[0].length,symbolCount=Number(options.symbolCount)||Math.max(...candidates.flat())+1,allowDuplicates=options.allowDuplicates!==false;const universe=options.universe||allCodes(length,symbolCount,allowDuplicates);let guesses=universe;if(universe.length>900&&candidates.length>180){const step=Math.ceil(universe.length/180);guesses=universe.filter((_,i)=>i%step===0);for(const c of candidates.slice(0,80))guesses.push(c);}let best=guesses[0],bestWorst=Infinity,bestEntropy=-Infinity,bestCandidate=false;for(const guess of guesses){const buckets=new Map();for(const code of candidates){const key=bucketKey(feedback(code,guess));buckets.set(key,(buckets.get(key)||0)+1);}let worst=0,entropy=0;for(const n of buckets.values()){worst=Math.max(worst,n);const p=n/candidates.length;entropy-=p*Math.log2(p);}const inCandidates=candidates.some(c=>c.every((v,i)=>v===guess[i]));if(worst<bestWorst||(worst===bestWorst&&entropy>bestEntropy)||(worst===bestWorst&&entropy===bestEntropy&&inCandidates&&!bestCandidate)){best=guess;bestWorst=worst;bestEntropy=entropy;bestCandidate=inCandidates;}}return best.slice();}
function createGame(options){options=options||{};const length=Math.max(3,Math.min(6,Number(options.length)||4)),symbolCount=Math.max(length&&options.allowDuplicates===false?length:4,Math.min(8,Number(options.symbolCount)||6)),allowDuplicates=options.allowDuplicates!==false,attemptLimit=Math.max(6,Math.min(16,Number(options.attemptLimit)||10)),seed=options.seed==null?Date.now():options.seed;return{length,symbolCount,allowDuplicates,attemptLimit,secret:options.secret?options.secret.slice():makeSecret({length,symbolCount,allowDuplicates,seed}),guesses:[],won:false,over:false,seed};}
function submit(input,guess){const s={...input,secret:input.secret.slice(),guesses:input.guesses.map(g=>({...g,guess:g.guess.slice(),feedback:{...g.feedback}}))};if(s.over)throw new Error('Game over');if(!Array.isArray(guess)||guess.length!==s.length)throw new Error('Invalid guess');if(guess.some(v=>v<0||v>=s.symbolCount))throw new Error('Invalid symbol');if(!s.allowDuplicates&&new Set(guess).size!==guess.length)throw new Error('Duplicates disabled');const f=feedback(s.secret,guess);s.guesses.push({guess:guess.slice(),feedback:f});s.won=f.exact===s.length;s.over=s.won||s.guesses.length>=s.attemptLimit;return{state:s,feedback:f};}
function solve(secret,options){options=options||{};const length=secret.length,symbolCount=options.symbolCount||Math.max(...secret)+1,allowDuplicates=options.allowDuplicates!==false,universe=allCodes(length,symbolCount,allowDuplicates);let candidates=universe.slice(),history=[];for(let turn=0;turn<(options.maxTurns||12)&&candidates.length;turn++){const guess=chooseGuess(candidates,{symbolCount,allowDuplicates,universe});const f=feedback(secret,guess);history.push({guess,feedback:f,remaining:candidates.length});if(f.exact===length)return history;candidates=filterCandidates(candidates,guess,f);}return history;}
return{feedback,allCodes,filterCandidates,makeSecret,chooseGuess,createGame,submit,solve};
});
