(()=>{'use strict';const E=window.CipherloomEngine,$=id=>document.getElementById(id),KEY='obg.cipherloom.v1';const shapes=['●','▲','■','◆','★','⬢','✚','⬟'];let game=null,mode='break',composer=[],candidates=[],universe=[],makerStage=false,seed=20260819;
function hashText(t){let h=2166136261>>>0;for(const ch of String(t)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h||1;}function daily(){const d=new Date();return hashText(`${d.getUTCFullYear()}-${d.getUTCMonth()+1}-${d.getUTCDate()}`)}
function opts(){return{length:Number($('length').value),symbolCount:Number($('symbols').value),allowDuplicates:$('duplicates').checked,attemptLimit:10,seed};}
function save(){try{localStorage.setItem(KEY,JSON.stringify({game,mode,composer,candidates,seed,length:$('length').value,symbols:$('symbols').value,duplicates:$('duplicates').checked,makerStage}));}catch(_e){}}
function restore(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x?.game)return false;game=x.game;mode=x.mode;composer=x.composer||[];candidates=x.candidates||[];seed=x.seed||20260819;makerStage=!!x.makerStage;$('mode').value=mode;$('length').value=x.length||4;$('symbols').value=x.symbols||6;$('duplicates').checked=x.duplicates!==false;universe=E.allCodes(game.length,game.symbolCount,game.allowDuplicates);return true;}catch(_e){return false;}}
function setup(){mode=$('mode').value;composer=[];seed=Date.now()>>>0;makerStage=mode==='local'||mode==='solver';const o=opts();game=E.createGame(o);universe=E.allCodes(o.length,o.symbolCount,o.allowDuplicates);candidates=universe.slice();if(makerStage)game.secret=Array(o.length).fill(-1);render();save();}
function peg(v,hidden=false){return`<span class="peg ${hidden?'hidden':`s${v}`}" aria-label="${hidden?'hidden symbol':`symbol ${v+1}`}">${hidden?'?':shapes[v]}</span>`;}
function render(){const secret=$('secret');const reveal=game.over&&mode==='break';if(makerStage)secret.innerHTML=Array(game.length).fill(0).map(()=>peg(0,true)).join('');else secret.innerHTML=game.secret.map(v=>peg(v,!reveal)).join('');$('history').innerHTML=game.guesses.map((g,i)=>`<div class="row"><span class="row-number">${i+1}</span><div class="guess">${g.guess.map(v=>peg(v)).join('')}</div><div class="feedback"><span class="badge exact">Exact ${g.feedback.exact}</span><span class="badge near">Near ${g.feedback.partial}</span></div></div>`).join('');$('composer').innerHTML=composer.length?composer.map(v=>peg(v)).join(''):'<span style="color:#65738b">Choose symbols below…</span>';$('palette').innerHTML=Array.from({length:game.symbolCount},(_,v)=>`<button data-v="${v}" aria-label="Add symbol ${v+1}">${peg(v)}</button>`).join('');$('palette').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>add(Number(b.dataset.v))));$('attempts').textContent=`${game.guesses.length} / ${game.attemptLimit}`;$('remaining').textContent=makerStage?'Private':candidates.length.toLocaleString();$('solveStep').style.display=mode==='solver'&&!makerStage?'inline-block':'none';if(makerStage){$('turnTitle').textContent=mode==='solver'?'Set a private code':'Player 1 · set the code';$('status').textContent=`Choose ${game.length} symbols, then submit. The board will hide them before the next stage.`;$('submit').textContent='Lock code';}else if(game.over){$('turnTitle').textContent=game.won?'Code broken':'Attempts exhausted';$('status').textContent=game.won?`Solved in ${game.guesses.length} guesses.`:'The code is now revealed.';$('submit').textContent='Submit guess';}else{$('turnTitle').textContent=mode==='solver'?'Computer solver':mode==='local'?'Player 2 · break the code':'Break the code';$('status').textContent=mode==='solver'?'Press Solver step to let the computer choose an information-rich guess.':`Build a ${game.length}-symbol guess.`;$('submit').textContent='Submit guess';}save();}
function add(v){if(composer.length>=game.length||game.over)return;if(!game.allowDuplicates&&composer.includes(v))return;composer.push(v);render();}
function lockCode(){if(composer.length!==game.length)return status(`Choose exactly ${game.length} symbols.`);game.secret=composer.slice();composer=[];makerStage=false;candidates=universe.slice();render();}
function status(t){$('status').textContent=t;}
function submitGuess(guess){try{const r=E.submit(game,guess);game=r.state;candidates=E.filterCandidates(candidates,guess,r.feedback);composer=[];render();}catch(err){status(err.message);}}
function submit(){if(makerStage)return lockCode();if(mode==='solver')return solverStep();if(composer.length!==game.length)return status(`Choose exactly ${game.length} symbols.`);submitGuess(composer.slice());}
function solverStep(){if(mode!=='solver'||makerStage||game.over)return;const guess=E.chooseGuess(candidates,{symbolCount:game.symbolCount,allowDuplicates:game.allowDuplicates,universe});submitGuess(guess);}
$('clear').addEventListener('click',()=>{composer=[];render()});$('submit').addEventListener('click',submit);$('solveStep').addEventListener('click',solverStep);$('newGame').addEventListener('click',setup);$('mode').addEventListener('change',setup);$('length').addEventListener('change',setup);$('symbols').addEventListener('change',setup);$('duplicates').addEventListener('change',setup);$('daily').addEventListener('click',()=>{mode='break';$('mode').value='break';composer=[];seed=daily();makerStage=false;game=E.createGame({...opts(),seed});universe=E.allCodes(game.length,game.symbolCount,game.allowDuplicates);candidates=universe.slice();render();});if(!restore())setup();else render();})();
