(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BoxlineEngine=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
function createGame(options){options=options||{};const rows=Math.max(1,Math.min(6,Number(options.rows)||3)),cols=Math.max(1,Math.min(6,Number(options.cols)||3)),players=Math.max(2,Math.min(4,Number(options.players)||2));return{rows,cols,players,current:0,h:Array((rows+1)*cols).fill(-1),v:Array(rows*(cols+1)).fill(-1),boxes:Array(rows*cols).fill(-1),scores:Array(players).fill(0),moves:0,over:false};}
function clone(s){return{rows:s.rows,cols:s.cols,players:s.players,current:s.current,h:s.h.slice(),v:s.v.slice(),boxes:s.boxes.slice(),scores:s.scores.slice(),moves:s.moves,over:!!s.over};}
function hIndex(s,r,c){return r*s.cols+c;}function vIndex(s,r,c){return r*(s.cols+1)+c;}function bIndex(s,r,c){return r*s.cols+c;}
function edgeTaken(s,t,r,c){if(t==='h'){if(r<0||r>s.rows||c<0||c>=s.cols)return true;return s.h[hIndex(s,r,c)]!==-1;}if(t==='v'){if(r<0||r>=s.rows||c<0||c>s.cols)return true;return s.v[vIndex(s,r,c)]!==-1;}return true;}
function boxComplete(s,r,c){return edgeTaken(s,'h',r,c)&&edgeTaken(s,'h',r+1,c)&&edgeTaken(s,'v',r,c)&&edgeTaken(s,'v',r,c+1);}
function boxSides(s,r,c){let n=0;if(edgeTaken(s,'h',r,c))n++;if(edgeTaken(s,'h',r+1,c))n++;if(edgeTaken(s,'v',r,c))n++;if(edgeTaken(s,'v',r,c+1))n++;return n;}
function adjacentBoxes(s,t,r,c){const out=[];if(t==='h'){if(r>0)out.push([r-1,c]);if(r<s.rows)out.push([r,c]);}else{if(c>0)out.push([r,c-1]);if(c<s.cols)out.push([r,c]);}return out;}
function legalEdges(s){const out=[];for(let r=0;r<=s.rows;r++)for(let c=0;c<s.cols;c++)if(s.h[hIndex(s,r,c)]===-1)out.push({t:'h',r,c});for(let r=0;r<s.rows;r++)for(let c=0;c<=s.cols;c++)if(s.v[vIndex(s,r,c)]===-1)out.push({t:'v',r,c});return out;}
function playEdge(input,edge){const s=clone(input),{t,r,c}=edge||{};if(s.over)throw new Error('Game is over');if(!['h','v'].includes(t)||edgeTaken(s,t,r,c))throw new Error('Illegal edge');const p=s.current;if(t==='h')s.h[hIndex(s,r,c)]=p;else s.v[vIndex(s,r,c)]=p;let completed=0;for(const [br,bc] of adjacentBoxes(s,t,r,c)){const bi=bIndex(s,br,bc);if(s.boxes[bi]===-1&&boxComplete(s,br,bc)){s.boxes[bi]=p;s.scores[p]++;completed++;}}s.moves++;if(!completed)s.current=(s.current+1)%s.players;s.over=legalEdges(s).length===0;return{state:s,completed,extraTurn:completed>0};}
function giveawayCount(s,edge){if(edgeTaken(s,edge.t,edge.r,edge.c))return 99;let count=0;const temp=clone(s);if(edge.t==='h')temp.h[hIndex(temp,edge.r,edge.c)]=temp.current;else temp.v[vIndex(temp,edge.r,edge.c)]=temp.current;for(const [r,c] of adjacentBoxes(temp,edge.t,edge.r,edge.c)){if(temp.boxes[bIndex(temp,r,c)]===-1&&boxSides(temp,r,c)===3)count++;}return count;}
function completionCount(s,edge){let count=0;const temp=clone(s);if(edge.t==='h')temp.h[hIndex(temp,edge.r,edge.c)]=temp.current;else temp.v[vIndex(temp,edge.r,edge.c)]=temp.current;for(const [r,c] of adjacentBoxes(temp,edge.t,edge.r,edge.c)){if(temp.boxes[bIndex(temp,r,c)]===-1&&boxComplete(temp,r,c))count++;}return count;}
function heuristicMove(s){const edges=legalEdges(s);let best=edges[0],bestScore=-1e9;for(const e of edges){const take=completionCount(s,e),give=giveawayCount(s,e);let score=take*100-give*18;for(const [r,c] of adjacentBoxes(s,e.t,e.r,e.c))score-=boxSides(s,r,c)*0.15;if(score>bestScore){bestScore=score;best=e;}}return best;}
function evaluate(s,root){let value=(s.scores[root]-Math.max(...s.scores.filter((_,i)=>i!==root)))*100;for(let r=0;r<s.rows;r++)for(let c=0;c<s.cols;c++){if(s.boxes[bIndex(s,r,c)]===-1){const sides=boxSides(s,r,c);if(sides===3)value+=(s.current===root?8:-8);}}return value;}
function minimax(s,root,depth,alpha,beta){if(depth<=0||s.over)return evaluate(s,root);const edges=legalEdges(s);let best=s.current===root?-Infinity:Infinity;for(const e of edges){const n=playEdge(s,e).state;const d=depth-1;const val=minimax(n,root,d,alpha,beta);if(s.current===root){best=Math.max(best,val);alpha=Math.max(alpha,best);}else{best=Math.min(best,val);beta=Math.min(beta,best);}if(beta<=alpha)break;}return best;}
function botMove(s,difficulty,rng){const edges=legalEdges(s);if(!edges.length)return null;rng=rng||Math.random;if(difficulty==='easy')return edges[Math.floor(rng()*edges.length)];if(difficulty!=='hard'||edges.length>13)return heuristicMove(s);const root=s.current;let best=edges[0],bestVal=-Infinity;for(const e of edges){const n=playEdge(s,e).state;const val=minimax(n,root,Math.min(13,edges.length)-1,-Infinity,Infinity);if(val>bestVal){bestVal=val;best=e;}}return best;}
function edgeKey(e){return `${e.t}:${e.r}:${e.c}`;}
return{createGame,clone,legalEdges,playEdge,boxComplete,boxSides,giveawayCount,completionCount,botMove,edgeKey,hIndex,vIndex,bIndex};
});
