(()=>{'use strict';const E=window.BoxlineEngine,$=id=>document.getElementById(id),KEY='obg.boxline.v1';let state=null,mode='bot',thinking=false;const colors=['p0','p1','p2','p3'];
function setup(){const [rows,cols]=$('boardSize').value.split('x').map(Number);mode=$('mode').value;const players=mode==='local3'?3:mode==='local4'?4:2;state=E.createGame({rows,cols,players});thinking=false;render();save();}
function save(){try{localStorage.setItem(KEY,JSON.stringify({state,mode,size:$('boardSize').value,difficulty:$('difficulty').value}));}catch(_e){}}
function restore(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x?.state)return false;state=x.state;mode=x.mode||'bot';$('mode').value=mode;$('boardSize').value=x.size||`${state.rows}x${state.cols}`;$('difficulty').value=x.difficulty||'medium';return true;}catch(_e){return false;}}
function gridTemplate(){const cols=[];for(let c=0;c<state.cols;c++){cols.push('16px','1fr')}cols.push('16px');const rows=[];for(let r=0;r<state.rows;r++){rows.push('16px','1fr')}rows.push('16px');return{cols:cols.join(' '),rows:rows.join(' ')}}
function renderBoard(){const b=$('board'),tpl=gridTemplate();b.style.gridTemplateColumns=tpl.cols;b.style.gridTemplateRows=tpl.rows;let html='';for(let gr=0;gr<=state.rows*2;gr++){for(let gc=0;gc<=state.cols*2;gc++){const style=`grid-row:${gr+1};grid-column:${gc+1}`;if(gr%2===0&&gc%2===0){html+=`<div class="dot" style="${style}"></div>`;}else if(gr%2===0&&gc%2===1){const r=gr/2,c=(gc-1)/2,p=state.h[E.hIndex(state,r,c)];html+=`<button aria-label="Horizontal edge row ${r+1} column ${c+1}" class="edge h ${p>=0?'claimed '+colors[p]:''}" data-t="h" data-r="${r}" data-c="${c}" style="${style}"></button>`;}else if(gr%2===1&&gc%2===0){const r=(gr-1)/2,c=gc/2,p=state.v[E.vIndex(state,r,c)];html+=`<button aria-label="Vertical edge row ${r+1} column ${c+1}" class="edge v ${p>=0?'claimed '+colors[p]:''}" data-t="v" data-r="${r}" data-c="${c}" style="${style}"></button>`;}else{const r=(gr-1)/2,c=(gc-1)/2,p=state.boxes[E.bIndex(state,r,c)];html+=`<div class="box ${p>=0?colors[p]:''}" style="${style}">${p>=0?p+1:''}</div>`;}}}b.innerHTML=html;b.querySelectorAll('.edge:not(.claimed)').forEach(btn=>btn.addEventListener('click',()=>humanMove({t:btn.dataset.t,r:Number(btn.dataset.r),c:Number(btn.dataset.c)})));}
function winnerText(){const m=Math.max(...state.scores),wins=state.scores.map((s,i)=>s===m?i+1:null).filter(Boolean);return wins.length>1?`Tie between Players ${wins.join(' & ')} at ${m}.`:`Player ${wins[0]} wins ${m} boxes.`;}
function render(){renderBoard();$('scorebar').innerHTML=[0,1,2,3].map(i=>`<div class="score-item" ${i>=state.players?'hidden':''}><span>Player ${i+1}${mode==='bot'&&i===1?' · Bot':''}</span><strong>${i<state.players?state.scores[i]:'—'}</strong></div>`).join('');document.querySelectorAll('[hidden]').forEach(e=>e.style.display='none');$('p3Legend').style.display=state.players>=3?'flex':'none';$('p4Legend').style.display=state.players>=4?'flex':'none';if(state.over){$('turnTitle').textContent='Game complete';$('status').textContent=winnerText();}else{$('turnTitle').textContent=`Player ${state.current+1}${mode==='bot'&&state.current===1?' · Bot':''}`;$('status').textContent=thinking?'Computer is choosing…':'Choose any open edge.';}save();}
function humanMove(edge){if(thinking||state.over||(mode==='bot'&&state.current===1))return;apply(edge);}
function apply(edge){try{const r=E.playEdge(state,edge);state=r.state;render();if(mode==='bot'&&!state.over&&state.current===1)setTimeout(botTurn,180);}catch(_e){}}
function botTurn(){if(state.over||state.current!==1)return;thinking=true;render();setTimeout(()=>{const edge=E.botMove(state,$('difficulty').value);thinking=false;if(edge)apply(edge);},80);}
$('hint').addEventListener('click',()=>{if(state.over)return;const edge=E.botMove(state,'medium',()=>.5);if(edge)$('status').textContent=`Suggestion: ${edge.t==='h'?'horizontal':'vertical'} edge at row ${edge.r+1}, column ${edge.c+1}.`;});$('newGame').addEventListener('click',setup);$('mode').addEventListener('change',setup);$('boardSize').addEventListener('change',setup);if(!restore())setup();else{render();if(mode==='bot'&&!state.over&&state.current===1)setTimeout(botTurn,200);}})();
