(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Rummy500Engine=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
function seeded(seed){let x=(Number(seed)>>>0)||0x27182818;return()=>{x^=x<<13;x>>>=0;x^=x>>>17;x>>>=0;x^=x<<5;x>>>=0;return x/4294967296}}function rank(c){return c%13+1}function suit(c){return Math.floor(c/13)}function value(c){const r=rank(c);return r===1?15:r>=10?10:r}function deck(){return Array.from({length:52},(_,i)=>i)}function shuffle(a,seed){a=a.slice();const r=seeded(seed);for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function sortHand(h){return h.sort((a,b)=>suit(a)-suit(b)||rank(a)-rank(b))}
function validateMeld(cards){if(!Array.isArray(cards)||cards.length<3||new Set(cards).size!==cards.length)return null;const rs=cards.map(rank),ss=cards.map(suit);if(rs.every(r=>r===rs[0]))return{type:'set'};if(ss.every(s=>s===ss[0])){const sorted=rs.slice().sort((a,b)=>a-b);if(sorted.every((r,i)=>i===0||r===sorted[i-1]+1))return{type:'run'};if(sorted.includes(1)){const high=sorted.map(r=>r===1?14:r).sort((a,b)=>a-b);if(high.every((r,i)=>i===0||r===high[i-1]+1))return{type:'run'}}}return null}
function dealCount(players){return players===2?13:7}function createGame(o){o=o||{};const players=Math.max(2,Math.min(6,Number(o.players)||2)),d=shuffle(deck(),o.seed==null?Date.now():o.seed),hands=Array.from({length:players},()=>[]),n=dealCount(players);for(let k=0;k<n;k++)for(let p=0;p<players;p++)hands[p].push(d.pop());hands.forEach(sortHand);return{players,hands,stock:d,discard:[d.pop()],melds:[],roundMeldPoints:Array(players).fill(0),scores:Array(players).fill(0),target:Math.max(100,Number(o.target)||500),current:0,phase:'draw',mustMeldCard:null,cannotDiscardCard:null,recycles:0,round:0,roundOver:false,over:false,winner:null,history:[]}}
function clone(s){return{...s,hands:s.hands.map(h=>h.slice()),stock:s.stock.slice(),discard:s.discard.slice(),melds:s.melds.map(m=>({...m,cards:m.cards.slice()})),roundMeldPoints:s.roundMeldPoints.slice(),scores:s.scores.slice(),history:s.history.map(x=>({...x,cards:x.cards?x.cards.slice():undefined}))}}
function drawStock(input){const s=clone(input);if(s.phase!=='draw'||s.roundOver)throw new Error('Cannot draw');if(!s.stock.length){if(s.recycles>=1||s.discard.length<=1)return finishRound(s);const top=s.discard.pop(),rest=s.discard.splice(0);s.stock=shuffle(rest,Date.now());s.discard=[top];s.recycles++}const c=s.stock.pop();if(c==null)return finishRound(s);s.hands[s.current].push(c);sortHand(s.hands[s.current]);s.phase='action';s.mustMeldCard=null;s.cannotDiscardCard=null;s.history.push({type:'draw-stock',player:s.current});return s}
function drawDiscardFrom(input,index){const s=clone(input);if(s.phase!=='draw'||s.roundOver||index<0||index>=s.discard.length)throw new Error('Cannot draw discard');const originalLength=s.discard.length,picked=s.discard[index],take=s.discard.splice(index);s.hands[s.current].push(...take);sortHand(s.hands[s.current]);s.phase='action';s.mustMeldCard=index===originalLength-1?null:picked;s.cannotDiscardCard=index===originalLength-1?picked:null;s.history.push({type:'draw-discard',player:s.current,cards:take.slice(),picked});return s}
function ownsCards(hand,cards){const h=hand.slice();for(const c of cards){const i=h.indexOf(c);if(i<0)return false;h.splice(i,1)}return true}
function checkMust(s,cards){return s.mustMeldCard==null||cards.includes(s.mustMeldCard)}
function meld(input,cards){const s=clone(input),p=s.current,kind=validateMeld(cards);if(s.phase!=='action'||!kind||!ownsCards(s.hands[p],cards)||!checkMust(s,cards))throw new Error('Illegal meld');for(const c of cards)s.hands[p].splice(s.hands[p].indexOf(c),1);s.melds.push({owner:p,type:kind.type,cards:cards.slice()});s.roundMeldPoints[p]+=cards.reduce((n,c)=>n+value(c),0);if(s.mustMeldCard!=null&&cards.includes(s.mustMeldCard))s.mustMeldCard=null;if(s.cannotDiscardCard!=null&&cards.includes(s.cannotDiscardCard))s.cannotDiscardCard=null;s.history.push({type:'meld',player:p,cards:cards.slice()});return maybeGoOut(s,p)}
function layoff(input,card,meldIndex){const s=clone(input),p=s.current,m=s.melds[meldIndex];if(s.phase!=='action'||!m||!s.hands[p].includes(card)||!validateMeld(m.cards.concat(card))||(s.mustMeldCard!=null&&card!==s.mustMeldCard))throw new Error('Illegal layoff');s.hands[p].splice(s.hands[p].indexOf(card),1);m.cards.push(card);s.roundMeldPoints[p]+=value(card);if(s.mustMeldCard===card)s.mustMeldCard=null;if(s.cannotDiscardCard===card)s.cannotDiscardCard=null;s.history.push({type:'layoff',player:p,card,meldIndex});return maybeGoOut(s,p)}
function finishRound(s){for(let p=0;p<s.players;p++){const penalty=s.hands[p].reduce((n,c)=>n+value(c),0);s.scores[p]+=s.roundMeldPoints[p]-penalty}s.roundOver=true;s.phase='round-over';const high=Math.max(...s.scores);if(high>=s.target){const leaders=s.scores.map((v,i)=>v===high?i:-1).filter(i=>i>=0);if(leaders.length===1){s.over=true;s.winner=leaders[0];s.phase='game-over'}}return s}
function maybeGoOut(s,p){if(s.hands[p].length===0)return finishRound(s);return s}
function discardCard(input,card){const s=clone(input),p=s.current;if(s.phase!=='action'||s.roundOver||s.mustMeldCard!=null||card===s.cannotDiscardCard||!s.hands[p].includes(card))throw new Error('Illegal discard');s.hands[p].splice(s.hands[p].indexOf(card),1);s.discard.push(card);s.history.push({type:'discard',player:p,card});if(!s.hands[p].length)return finishRound(s);s.current=(p+1)%s.players;s.phase='draw';s.cannotDiscardCard=null;return s}
function nextRound(input,seed){if(!input.roundOver||input.over)throw new Error('Round not ready');const n=createGame({players:input.players,target:input.target,seed:seed==null?Date.now():seed});n.scores=input.scores.slice();n.round=input.round+1;return n}
function allMelds(hand){const out=[];for(let i=0;i<hand.length;i++)for(let j=i+1;j<hand.length;j++)for(let k=j+1;k<hand.length;k++){const tri=[hand[i],hand[j],hand[k]];if(validateMeld(tri))out.push(tri)}for(const m of out.slice()){let cur=m.slice();for(const c of hand)if(!cur.includes(c)&&validateMeld(cur.concat(c)))cur.push(c);if(cur.length>m.length)out.push(cur)}return out.sort((a,b)=>b.reduce((n,c)=>n+value(c),0)-a.reduce((n,c)=>n+value(c),0))}
function botDraw(s,p,difficulty){const top=s.discard.at(-1),hand=s.hands[p],withTop=top==null?[]:allMelds(hand.concat(top)).filter(m=>m.includes(top));if(top!=null&&withTop.length)return{source:'discard',index:s.discard.length-1};if(difficulty==='hard'){for(let i=Math.max(0,s.discard.length-4);i<s.discard.length-1;i++){const c=s.discard[i];if(allMelds(hand.concat(c)).some(m=>m.includes(c)))return{source:'discard',index:i}}}return{source:'stock'}}
function botActions(input,difficulty){let s=clone(input),guard=0;while(s.phase==='action'&&!s.roundOver&&guard++<20){const p=s.current,ms=allMelds(s.hands[p]).filter(m=>s.mustMeldCard==null||m.includes(s.mustMeldCard));if(ms.length){s=meld(s,ms[0]);continue}let laid=false;for(let i=0;i<s.melds.length&&!laid;i++)for(const c of s.hands[p])if(validateMeld(s.melds[i].cards.concat(c))&&(s.mustMeldCard==null||c===s.mustMeldCard)){s=layoff(s,c,i);laid=true;break}if(laid)continue;if(s.mustMeldCard!=null)throw new Error('Bot cannot satisfy buried discard pickup');const card=s.hands[p].filter(c=>c!==s.cannotDiscardCard).sort((a,b)=>value(b)-value(a))[0];if(card==null)throw new Error('Bot has no legal discard');return discardCard(s,card)}return s}
function playerView(s,p){return{players:s.players,current:s.current,phase:s.phase,hand:s.hands[p].slice(),handCounts:s.hands.map(h=>h.length),stockCount:s.stock.length,discard:s.discard.slice(),melds:s.melds.map(m=>({...m,cards:m.cards.slice()})),roundMeldPoints:s.roundMeldPoints.slice(),scores:s.scores.slice(),mustMeldCard:p===s.current?s.mustMeldCard:null,cannotDiscardCard:p===s.current?s.cannotDiscardCard:null,roundOver:s.roundOver,over:s.over,winner:s.winner};}
return{rank,suit,value,deck,shuffle,validateMeld,dealCount,createGame,clone,drawStock,drawDiscardFrom,meld,layoff,discardCard,nextRound,allMelds,botDraw,botActions,playerView};});