(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.FiveDiceV2=api;api.mount()}})(typeof globalThis!=='undefined'?globalThis:this,function(){
const CATS=[['ones','Ones'],['twos','Twos'],['threes','Threes'],['fours','Fours'],['fives','Fives'],['sixes','Sixes'],['threeKind','Three of a kind'],['fourKind','Four of a kind'],['fullHouse','Full house'],['smallStraight','Small straight'],['largeStraight','Large straight'],['fiveKind','Five of a kind'],['chance','Chance']];
function counts(d){const c=Array(7).fill(0);d.forEach(x=>c[x]++);return c}
function scoreCategory(d,cat){const c=counts(d),sum=d.reduce((a,b)=>a+b,0),uniq=[...new Set(d)].sort((a,b)=>a-b);const n={ones:1,twos:2,threes:3,fours:4,fives:5,sixes:6}[cat];if(n)return c[n]*n;if(cat==='threeKind')return c.some(x=>x>=3)?sum:0;if(cat==='fourKind')return c.some(x=>x>=4)?sum:0;if(cat==='fullHouse')return c.includes(3)&&c.includes(2)?25:0;if(cat==='smallStraight'){const s=uniq.join('');return ['1234','2345','3456'].some(x=>s.includes(x))?30:0}if(cat==='largeStraight')return uniq.length===5&&(uniq[4]-uniq[0]===4)?40:0;if(cat==='fiveKind')return c.includes(5)?50:0;if(cat==='chance')return sum;return 0}
function mount(){if(typeof document==='undefined')return;const diceEl=document.getElementById('dice'),card=document.getElementById('scorecard'),rollBtn=document.getElementById('roll'),status=document.getElementById('status'),totalEl=document.getElementById('total'),rollState=document.getElementById('rollState');if(!diceEl)return;let dice=[1,1,1,1,1],held=[false,false,false,false,false],rolls=0,scores={};
function total(){return Object.values(scores).reduce((a,b)=>a+b,0)}
function render(){diceEl.innerHTML=dice.map((v,i)=>`<button class="fd-die${held[i]?' held':''}" data-die="${i}" aria-pressed="${held[i]}">${v}</button>`).join('');rollState.textContent=`${rolls} / 3`;totalEl.textContent=total();rollBtn.disabled=rolls>=3;card.innerHTML=CATS.map(([k,label])=>{const used=k in scores,p=rolls?scoreCategory(dice,k):0;return`<button class="fd-row${used?' used':''}" data-cat="${k}" ${used||!rolls?'disabled':''}><span>${label}</span><strong class="${used?'':'preview'}">${used?scores[k]:p}</strong></button>`}).join('');if(Object.keys(scores).length===CATS.length)status.textContent=`Scorecard complete · ${total()} points`}
function roll(){if(rolls>=3)return;dice=dice.map((v,i)=>held[i]?v:1+Math.floor(Math.random()*6));rolls++;status.textContent=rolls===3?'Choose a scoring row':'Hold what you like or roll again';render()}
function score(cat){if(!rolls||cat in scores)return;scores[cat]=scoreCategory(dice,cat);dice=[1,1,1,1,1];held=[false,false,false,false,false];rolls=0;status.textContent=Object.keys(scores).length===CATS.length?'Scorecard complete':'Next turn · roll the dice';render()}
diceEl.addEventListener('click',e=>{const b=e.target.closest('[data-die]');if(!b||!rolls)return;const i=Number(b.dataset.die);held[i]=!held[i];render()});card.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b)score(b.dataset.cat)});rollBtn.addEventListener('click',roll);document.getElementById('newGame')?.addEventListener('click',()=>{scores={};rolls=0;held=held.map(()=>false);status.textContent='Roll the dice';render()});render()}
return{CATS,scoreCategory,mount};
});
