(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.ThreadmarkV2=api;api.mount()}})(typeof globalThis!=='undefined'?globalThis:this,function(){
const WORDS='ANCHOR APPLE ASTRONAUT BELL BRIDGE BRUSH CABLE CASTLE CLOUD COMET CROWN DRAGON ENGINE FIELD FLAME FOREST GLASS HARBOR HONEY HORSE KEY LANTERN LASER LEAF MAPLE MOON MOUNTAIN NEEDLE OCEAN ORBIT PAPER PIANO RIVER ROCKET ROOT SCALE SHADOW SHIP SIGNAL SNOW SPARK STONE STORM TABLE TOWER TRACK TRAIN WAVE WHALE WHEEL WIND WING'.split(' ');
function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createState(words=shuffle(WORDS).slice(0,25)){const roles=['red',...Array(8).fill('red'),...Array(8).fill('blue'),...Array(7).fill('neutral'),'assassin'].slice(0,words.length);const shuffled=shuffle(roles);return{words:[...words],roles:Object.fromEntries(words.map((w,i)=>[w,shuffled[i]||'neutral'])),revealed:[],team:'red',ended:false,winner:null}}
function remaining(s,team){return s.words.filter(w=>s.roles[w]===team&&!s.revealed.includes(w)).length}
function reveal(state,word){if(state.ended||state.revealed.includes(word)||!state.roles[word])return state;const s={...state,revealed:[...state.revealed,word]},role=s.roles[word],other=s.team==='red'?'blue':'red';if(role==='assassin'){s.ended=true;s.winner=other;return s}if(role===other||role==='neutral')s.team=other;if(remaining(s,'red')===0){s.ended=true;s.winner='red'}if(remaining(s,'blue')===0){s.ended=true;s.winner='blue'}return s}
function mount(){if(typeof document==='undefined')return;const grid=document.getElementById('grid'),status=document.getElementById('status');if(!grid)return;let s=createState();
function render(){grid.classList.toggle('navigator',document.getElementById('spymaster').checked);grid.innerHTML=s.words.map(w=>{const rev=s.revealed.includes(w),role=s.roles[w];return`<button class="tm-word${rev?' revealed '+role:''}" data-word="${w}" data-role="${role}" ${rev||s.ended?'disabled':''}>${w}</button>`}).join('');document.getElementById('redLeft').textContent=remaining(s,'red');document.getElementById('blueLeft').textContent=remaining(s,'blue');document.getElementById('redTeam').classList.toggle('on',s.team==='red'&&!s.ended);document.getElementById('blueTeam').classList.toggle('on',s.team==='blue'&&!s.ended);status.textContent=s.ended?`${s.winner.toUpperCase()} team wins`: `${s.team.toUpperCase()} team is guessing`}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-word]');if(!b)return;s=reveal(s,b.dataset.word);render()});document.getElementById('spymaster').addEventListener('change',render);document.getElementById('endTurn').addEventListener('click',()=>{if(s.ended)return;s={...s,team:s.team==='red'?'blue':'red'};render()});document.getElementById('newGame').addEventListener('click',()=>{s=createState();render()});render()}
return{WORDS,createState,reveal,remaining,mount};
});
