(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.HueBreakV2=api;api.mount()}})(typeof globalThis!=='undefined'?globalThis:this,function(){
const HUES=['coral','ocean','sun','mint'];
function canPlay(card,top,currentHue){return card.hue==='wild'||card.hue===currentHue||card.value===top.value}
function makeDeck(){const d=[];for(const h of HUES){d.push({hue:h,kind:'number',value:'0'});for(let n=1;n<=9;n++)for(let k=0;k<2;k++)d.push({hue:h,kind:'number',value:String(n)});for(const a of ['skip','reverse','draw2'])for(let k=0;k<2;k++)d.push({hue:h,kind:'action',value:a})}for(let i=0;i<4;i++)d.push({hue:'wild',kind:'wild',value:'wild'});return d}
function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function mount(){if(typeof document==='undefined')return;const handEl=document.getElementById('hand'),discardEl=document.getElementById('discard'),oppEl=document.getElementById('opponents'),status=document.getElementById('status'),turnEl=document.getElementById('turn'),hueEl=document.getElementById('currentHue'),dirEl=document.getElementById('direction'),ring=document.getElementById('hueRing');if(!handEl)return;let s;
function label(c){return c.value==='draw2'?'+2':c.value==='reverse'?'↻':c.value==='skip'?'⊘':c.value==='wild'?'✦':c.value}
function cardHtml(c,i,clickable=true){return`<button class="hb-card ${c.hue}" data-hue="${c.hue}" ${clickable?`data-card="${i}"`:''}>${label(c)}</button>`}
function mostHue(hand){const c=Object.fromEntries(HUES.map(h=>[h,0]));hand.forEach(x=>{if(c[x.hue]!=null)c[x.hue]++});return HUES.sort((a,b)=>c[b]-c[a])[0]}
function drawCard(p,n=1){for(let k=0;k<n;k++){if(!s.deck.length){const top=s.discard.pop();s.deck=shuffle(s.discard);s.discard=[top]}const c=s.deck.pop();if(c)s.hands[p].push(c)}}
function advance(step=1){for(let i=0;i<step;i++)s.turn=(s.turn+s.direction+s.hands.length)%s.hands.length}
function playCard(p,index){const c=s.hands[p][index],top=s.discard.at(-1);if(!c||!canPlay(c,top,s.currentHue))return false;s.hands[p].splice(index,1);s.discard.push(c);s.currentHue=c.hue==='wild'?mostHue(s.hands[p]):c.hue;if(!s.hands[p].length){s.over=true;s.winner=p;status.textContent=p===0?'You cleared your hand':'Opponent wins';render();return true}let step=1;if(c.value==='reverse'){s.direction*=-1;if(s.hands.length===2)step=2}else if(c.value==='skip')step=2;else if(c.value==='draw2'){advance();drawCard(s.turn,2);step=1}advance(step);return true}
function render(){const top=s.discard.at(-1);discardEl.innerHTML=cardHtml(top,0,false);handEl.innerHTML=s.hands[0].map((c,i)=>cardHtml(c,i)).join('');document.getElementById('handCount').textContent=`${s.hands[0].length} cards`;oppEl.innerHTML=s.hands.slice(1).map((h,i)=>`<div class="hb-opponent${s.turn===i+1?' on':''}"><strong>Player ${i+2}</strong><small>${h.length} cards</small></div>`).join('');turnEl.textContent=s.turn===0?'You':`Player ${s.turn+1}`;hueEl.textContent=s.currentHue;dirEl.textContent=s.direction===1?'Clockwise':'Counter-clockwise';const colors={coral:'#ff7668',ocean:'#57b4ef',sun:'#ffd067',mint:'#6ae2a1'};ring.style.setProperty('--hue',colors[s.currentHue]||'#80e6b7');if(!s.over)status.textContent=s.turn===0?'Play a match or draw':'Opponent thinking…'}
function bots(){if(s.over||s.turn===0)return;const p=s.turn,top=s.discard.at(-1),i=s.hands[p].findIndex(c=>canPlay(c,top,s.currentHue));if(i>=0)playCard(p,i);else{drawCard(p);const j=s.hands[p].findIndex(c=>canPlay(c,s.discard.at(-1),s.currentHue));if(j>=0)playCard(p,j);else advance()}render();if(!s.over&&s.turn!==0)setTimeout(bots,360)}
function newGame(){const players=Number(document.getElementById('players').value)||4,deck=shuffle(makeDeck()),hands=Array.from({length:players},()=>[]);for(let n=0;n<7;n++)for(const h of hands)h.push(deck.pop());let first=deck.pop();while(first.hue==='wild'||first.kind==='action'){deck.unshift(first);first=deck.pop()}s={deck,hands,discard:[first],currentHue:first.hue,turn:0,direction:1,over:false,winner:null};render()}
handEl.addEventListener('click',e=>{const b=e.target.closest('[data-card]');if(!b||s.turn!==0||s.over)return;if(playCard(0,Number(b.dataset.card))){render();setTimeout(bots,360)}});document.getElementById('draw').addEventListener('click',()=>{if(s.turn!==0||s.over)return;drawCard(0);const c=s.hands[0].at(-1);if(canPlay(c,s.discard.at(-1),s.currentHue))status.textContent='Drawn card is playable';else{advance();render();setTimeout(bots,360)}render()});document.getElementById('newGame')?.addEventListener('click',newGame);document.getElementById('players')?.addEventListener('change',newGame);newGame()}
return{HUES,canPlay,makeDeck,mount};
});
